apiVersion: ENC[AES256_GCM,data:T9g=,iv:0qlkEV+kGRvYKL1bAGOxyXRzjMPUxaAkrxxWwfJa9vA=,tag:2cn04BVbmjymm6iR4jcv2Q==,type:str]
kind: ENC[AES256_GCM,data:oiwaauJ2,iv:rPL7oa8pujdHo/ABdtX28DJI0tB9fk8RX8JNUmL4fXs=,tag:rwr28kHM4IEXCWslr4o2KQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9e5wcjkCjjRKItEIVYqgKUm6,iv:CCxbh9ACRQdPvtTKSjhEIZfHODCfhHyp7iLlkqGcO4w=,tag:v2qRdM/jAHe5Nzg6CSC1Bg==,type:str]
    namespace: ENC[AES256_GCM,data:OF93UiTEgg==,iv:bOAqoxsKXBaPQqaSxkAtLIivE9sHk8rtwe7e0fTu9hg=,tag:o/WrBnOOsGApVpTbfL8SsA==,type:str]
type: ENC[AES256_GCM,data:LcP32Jzs,iv:k0bnrRPBARme52AsUoxyHPsg22QzYnlh9ZH9Q7o+weg=,tag:x5mKgKNv8y8/pXUtn8bRrA==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:BqUmRsLs,iv:B5G0C9jT+7DX8nHLs2DTCtCCSiIn1r346ghcDOMSfdM=,tag:rVWPhdSGRFT3LA9SGv0cnQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:92oyrR6KVMe9tKuvIQ4xujaIwb6HGrSX9rQKzAS7hIo=,iv:mCO8DkDi1V2/tLaMjphaOo4xAdo/9tEepjU0JyGqvd4=,tag:hCCmsuD5y7xNI+r/Ap4ROA==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:NMcSeOzLkCXMau798vuB0sLiU2gBNuecrf89hUNVPzw=,iv:lO79DBZmgZd6ZGr5mWzsHQDlU7lKsF86ed8qlGGZTrs=,tag:+FVIvP8dkYTUdZlZLzoLtg==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:vwAF+deE80Z5U6fhbpn1kCf4E5oM8keEgOhhoqADTlJTcEkk50VaLMaVo+yCwVXFKzfvze3a5FEVtXW+poWhlQ==,iv:RSUn6/ykHSXUZviOodrspu732BOgp6euvSMQUMge4Jg=,tag:W0AhHarDRuUCRTOolNHpww==,type:str]
    TOSSPAYMENTS_SECRET_KEY: ENC[AES256_GCM,data:PWwksnZudpcjRpzyS2PZWddwWYuB2SRWMUA74Og9uu/bzNVW,iv:dn1d5DHt2eF/rA1xmKw5Y9SXf7PLkfrHkcvmfRz7g6g=,tag:XLVuPOuSkCXz58iZD8CVDA==,type:str]
    PAYMENT_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:zLCJGypD1v++qJYEoy6MsnaGac9XQxERH92H7Fey+mI=,iv:BkC2ss5yAcL8YyRlRIV+aaOTPmWwayE8d0MPgP9oPpk=,tag:5B09se21fGt+gygNncBCJw==,type:str]
    PAYMENT_ENCRYPTION_SALT: ENC[AES256_GCM,data:MojyUL8ehkwiO5YoeG5l3pkJT8NNnT/NvP6W3gSJ0RM=,iv:Z2YY7Tk0jfgR7hXG5YHoq2VCSDf65c+qhuuRNxH5Xo4=,tag:0l7ehT8YIYJW/zs8mQSBNw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:XL+T2SZ/5lRiRQ==,iv:aTh5EG+9CjHyBJlrb7KRxUHYI5x/33fwl10uS+H4+rY=,tag:Rk3MOFH6TPyULgXSrJfWqA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:rq9EAg5oa/3hwA==,iv:ImliFxP037lSV+U3tBjO9zFLtfvNy2rqmqzuPbI9YPY=,tag:uFqH09KCaXPVmJdP7D3h/g==,type:str]
sops:
    age:
        - recipient: age1vxtgy82n4vprjft3pp34hnwcneu6ltf5fe2k0xwzxuddf3w8ksss8xw830
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNW12d2dDNll5QTcrdVFM
            ODRVWWcvdXVSMVFvL1ozbWtVMjdCdktzU21FCmpXMnhpSVB2MDZZaElaVis1Sklw
            ektVd24vTDFxMXFJNVBzSVhHbTBETnMKLS0tIG56WGl3QzB0R2grbkZaS256dHVQ
            YmdGSFRmVSt6RnFNeHZ1a0MzK3RyQlUKhzu6XrAN2I0QMT8jn3mB+7LmGrowQnoC
            f04I1it53HwrYlUbYD+cHTSSFLE9nbyCwUHd+RigdRLnvpuRxCcZUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15guk5yt7drtwmfl7uu3x03snfmtd2zdkk7lnay9tng03kzce8gqq63hw6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTEtWT0wrMTFXVE5ZR2FR
            NTJUbndmcExyTDNvT3dLUXRoaUhPTmtVUERjCjRGdWFYRU8rd09HKzZvMDRUMkV6
            VkpNRGRwZDhuRnJ5UzV0UytndDZ3MzAKLS0tIEMybkVkdDZPbml0YWoyM0hKL0xw
            Zk1jZ2EwY2ozMGdPTkU0Y2NFc2F0RVUKVOu9TgwrDPDXGCVZvp7014k6d1m/Qs7U
            j97JLbj/LIw7vw6bkOdIZ5LKia9omLhkc5zc/CzKoQBxRhSHozSk8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T08:40:12Z"
    mac: ENC[AES256_GCM,data:vO45zNh2qxwx1jB138VMWbpR3Vxxw4xiykWQumM16g59YiIDVmG/EYgrMT84nqpsCHkR+KMRAlQ8pmc+ooWgsi6cLqGAv/B5/yA5NvyWLtVeTvtcYZ3wUj5PwcXDR/8GC5Uj/1CHXLDEPK2e+ryota2Yi1FpdPwZSRaZgHdSFkI=,iv:dtBMXVrkFeok80U1uNxERv1izTghZluCd0QL9Q3Uhqc=,tag:OzpLNp9Jm7X4XIw+B2vb9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
