apiVersion: ENC[AES256_GCM,data:JLs=,iv:ccMtO5gSnxUHUlSN1HXGo6H3X6b5sFyTL+Q5RsNZKa8=,tag:sknkmWZcxYsM6NmPcHYu2w==,type:str]
kind: ENC[AES256_GCM,data:+iDrQfQ7,iv:zCYtIWLKJwn0WJvatqtdlvvCQ8qXq/ZzMPt0dKoK9ko=,tag:OVj8QcYAYrYnKNocClIeuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ze0Z7c29khugjEhcYQhW9WJ5,iv:xmMzJzuTPgigCHsPmKU+YIyZS1ETRLXDqumSuDJ0VaM=,tag:ko6sZmxWraBqf8ZWm+Qv6w==,type:str]
    namespace: ENC[AES256_GCM,data:0CeCL8HZBg==,iv:3cn9wlSqA9YgJgwmLo463Kto399elsFuJN+zrMlLu+I=,tag:wsnY6vYOJLehzNNGOPC7fA==,type:str]
type: ENC[AES256_GCM,data:rBmy69iq,iv:lRnGCwqsU2f349fMYW/WP2Hu8myFWZbLUx30BsA5yiE=,tag:olHaKUTGaZAjTfGb5IV9OA==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:CQWgkwO+,iv:2r33mOgEplvO/sW1XN7AIeYPsyZKvXDKsGHpIs/UhuA=,tag:/EuOT+07OUVaxV33XnzFNg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:8IswwZf3hkCVlgGBxbE8OkUCsjaYgXwnOuyR8gCZjKI=,iv:gNfb5TJQrisLIFymot3TiqjxjjiYqzpvUlhGVwMk/JE=,tag:Fj7sAXwYuQIiuv7PIIo0Wg==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:aKVl9fmlE3yobzhBoEabGsSeAhNdoJbgjOtlCnF2pl8=,iv:DR5PbI8jh31RnvBc5mxqnjrh8J46PM97dMr5I9HtgIQ=,tag:CpkISNq4y4PQkBu5EItoxg==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:rkf/KMwnTc2I96SC2kx2QNv9xZiqsIT/jZCALCywXKMkNobqCmD+R0HKRqoffqSQiZkQ8FWmH1ieeVWLMVdwSQ==,iv:5gefBWO+Vucdc++ttK5SBhCwrTGcgACp0cMJiPXY8fc=,tag:epOpDuiNF4hoHCT+ddBPDQ==,type:str]
    TOSSPAYMENTS_SECRET_KEY: ENC[AES256_GCM,data:d+unDtP3GGZRpfMjebho92tf3ePwJlx7CNUrS5H7sbKDvqEe,iv:x6LvZgGiSfzrPpaAoAVcWvUSFyKOkcMj/cD2z76OUQY=,tag:xvsHNYcGy+iwllyeZ9HhxA==,type:str]
    PAYMENT_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:JSNMs5rUIbXlNGZnK6HpJiRjc1kvCwhioQDxSRDekmI=,iv:VBn98ZiFB4Ir+hC0odCUX0PU4+wnY1E8zl2kJJYr1xc=,tag:03PuIg2nCZP5NqovRp+GKQ==,type:str]
    PAYMENT_ENCRYPTION_SALT: ENC[AES256_GCM,data:MAMSOr4cXvJMQL6WJaT/5j8cr/dkkfm8Za7tB9h9CPA=,iv:1Gh16S7Cj3SHmYlBmab2f4SRkaeZfY6j3gQZemOc3nI=,tag:xDerPnU0hQfWDrKpPQcREw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:xcC8JJzp06CJiA==,iv:6HtUE4qoBjvXO4WFJ7f51TJduQHQYVXhpIEr+Jdjf/o=,tag:4zZszheKWkintLDoSV9bXA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:mEdinlv1mp6kqg==,iv:yNJxLLOXEwzA0F8UV7D50c79U3mSPbzxu4bFrENLHLo=,tag:oVChDeg18TcqjfwI549hkg==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT1NaRzAxR0ZjMjJVTldH
            SlBpNTJHbGdXUG9yaGxKblNXMThJWWcvNlY4Ck5maTlTOE5QejkxVTBWTlZhK0lQ
            WWhhZHErZklxZXc0SHVrR2dtTVFCS3MKLS0tIEh1WmdBb1ZrdnVuSGNtUTVWS2lG
            ZU1SM0U0eExzK0VoMFU1WFpGV20zaTQKJeZ0FKxfIuFEQPqULLazba5O/r0HCUFJ
            L5SzE10fIWYIY82jaqTtW0yDslW2dl6ektM7z5v9muQZEzyKOaawxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:35Z"
    mac: ENC[AES256_GCM,data:VIAJM9GEARCGhoMhV5dFnEZMGAXla9MzTEY8OUqVz9szgNtULIXzOn6gDZq069bqsF+/4fi0PzQnOY0h4+w4yGrjTc8+fso8PDTYh6SqRMKb1zja28J6QWp6QOjAu7sxYLo4s5Dm8grTUzvvTnlgD6FMqoUdpw/u35oOz3VT+Ks=,iv:kvAFOUW8cUFvt5z4foTEBmd0wfXosFRVTRWzEWz7Su4=,tag:xFtfP4BAwWsS1Qlr292uUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
