apiVersion: ENC[AES256_GCM,data:0Ss=,iv:tE4rPhcYGJLyKS0OK6S7Raw3iWLUcVtwhsykP1GuJyE=,tag:J1JpAhfieeWq53+/LBOckA==,type:str]
kind: ENC[AES256_GCM,data:O6C9EpB8,iv:KG2NXjc6dmOHhzFeDF4UkyPecbdsvVzsFXPpWlwln8s=,tag:NOu8Z2xokkpznQkDybv3fQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k6kKliqgUFgikg/MRNFW,iv:wiXjEir9ZFhwyHSN7lfi3Ck5Lw7QC5TE+KWU9FYxO8U=,tag:dtf58+OGl54ivXhT0nxGmQ==,type:str]
    namespace: ENC[AES256_GCM,data:RYY0JLXwnQ==,iv:TIRR3L5ZWDJ7k9DRg4yMyKMoelc6j8Wtsq8j3U7i9bU=,tag:Wq7d7ZlGer2XAMTnMp0rWw==,type:str]
type: ENC[AES256_GCM,data:ikGX8vOG,iv:0HG5yQS1Y0SKm6JWVpRYv9xq8NQL/yNEqCkulBI+PsQ=,tag:hB4mTQsdZn4DIRNiCEGbbA==,type:str]
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:cB3PKkGyEWRDyutIStvbQA==,iv:C7dXNSytEvrCO7gvOjQBX8h0gKZmvrOEbhfrCmJO9CM=,tag:B2UJ1/xWDryBmlGNMNNHoQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JOCsewIn3q4aZ7SpVKXFVQ==,iv:Id2kB67L3g4QXp97+o76L7MNuqbGzCElhgCwziYQFZE=,tag:UaA1bRaBurvqj/fN2MI3fA==,type:str]
sops:
    age:
        - recipient: age1vxtgy82n4vprjft3pp34hnwcneu6ltf5fe2k0xwzxuddf3w8ksss8xw830
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYmtmbTcvYi9sY2V2Nzlv
            TCt0OHdkakFQbjNNeFFkdmxEL05lL3hjU2pNCmpKQ3RGYmNGZFhBR0pvNFRVb3ZS
            SW1sS1lFNWFjOTEva0xLNmhuZnBnZ0kKLS0tIEdnbTNnL1FwTHBLblMyUnMvaTcx
            RzJoY0pUQlZzSGdEODBlcldTc29zWGMKIRLGaxKnzVXaSHfm5opk4KSaK285GXup
            /Foln0Xi1z5+mAHMFeWn664TaQ0LH/lbjwl8D6wSATopCgTF7XEqpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15guk5yt7drtwmfl7uu3x03snfmtd2zdkk7lnay9tng03kzce8gqq63hw6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGhzQ1ROV0d0S0RPOFV3
            YTRWeUUvcXhVZzhUMW1qOUQ2WVdiS1BVQ0RVCjRaUm9CYVdhejFHaExIQytYYzdy
            WGdrbm9xOHloTXJNNUxKQjdrV0YvNkEKLS0tIHV6K0ZUaCtKZmJTWVpHdWRnaXpE
            QUpEWS83cnNMQ1ZpbTJidUhJcHRKUWMKXCnFyEY4bULcOLOfg15Qbd8jod0Dt1gM
            9cC0s/7Ed87FFWVm+re272NBN+L/9q94ixk2VTfhxRXq0s/uwyY09Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T08:40:12Z"
    mac: ENC[AES256_GCM,data:FhEJWQrlAApDIq4MHJ6LOu+npqZ4Kh2sbzmp0R5rdgBoaSNwv4CdrtU/QTNwDUpfQTKY8FAcZPRvgf5EtJPpC7x//xah8X+MgZ9v5Tgu++TxeApQChQ9A7epAynjBWW4JY4xR+h7uqQ07ZuViY/I2l7HoqJ1yOqoNRHmk+sBQlc=,iv:iw07GyE8mHgkJqxSxtEqABeE4fAHGXO5gDV9gXEEc2c=,tag:2oSC+ZJsMCucCBtvHT/FwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
