apiVersion: ENC[AES256_GCM,data:wx0=,iv:T3cnDoHhAk2HQEXRLjuZkAosPv+jhcVVnx6jAjsKM6M=,tag:vVxZRex4sLfaT6/LNW8iHg==,type:str]
kind: ENC[AES256_GCM,data:BBO1S2vl,iv:zcnIdpF92Qgorjh6+3QuyOP9HoC+m6DLdoiLGxHicug=,tag:7gKpmQCrY0bua88dt65HNQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iQQO6bShpDgl5ue9OD78,iv:IIUwqbanQsirFyzLfk0KeqSGvyZM51SAgAem5oTraOM=,tag:Og6FSmcxmpdXBPtz1zPOGA==,type:str]
    namespace: ENC[AES256_GCM,data:bhYvDxEv0g==,iv:o2rPYsVzu1NYiNDYoo/LFfkSuOk2FVLrHm6bFhvWec8=,tag:aLArXyslpIvakHQi6sEoUQ==,type:str]
type: ENC[AES256_GCM,data:PHaDw+HM,iv:uCiafOGKNHLZKQ+jairvsk6ICLZbpECiTHcGTbnErgA=,tag:9yxMZ8sbpMPxNbsaYHCUHw==,type:str]
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:3HQCV56jM87iqjw9Czi/VA==,iv:Wmg/OjDJCfEAnxjhWHutO7QPJYcWvaw6O21ugP3CuZc=,tag:ruyRvKZZcJ7qOAHu0nEIDg==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:0z2n0D9rEP4w2TtKnsUcoQ==,iv:01b7Vl/Uj4FHyPs+bKzWkhc41GuucwyEyKkBl/dO7nA=,tag:fHbyYwVAUfDKSTy/CPKp/g==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3A4d2xRSTRoRVFpc2FF
            L2V3eWxsdFZISE1lTDZ5UDFPc0Q5NXBMeDFzCmF4RnVEQkxERkUzaWFYNGdlZllx
            Zk95VkZPdGdYY0NJUk1wbC9FVmNWYlkKLS0tIDd2WHdpZEhxSjNvQldoSlVoYnZs
            dk9KMXE2N210T1VnRjM2ZGY4OUljcFEKByD8QpgdKSYDGO5KQGEyaP7aPy9w3HSz
            qYHnf/VLRXL+RwhfRJmhPiKxBQScd7w0V3cVP0acl9041m/cIWhkVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:35Z"
    mac: ENC[AES256_GCM,data:+KGdOD3hGDJGsuqwt7TVGrUhlLi7zGeIpCcloHU8r963WpcwoSGXnobrjlt3oHdThXxGssXl+ff8XWyds033aWPB10IX7Tv/nSMZHnIb5BUqw5VsbsuCgO6MbuE505zAc/yc428HdNcFOwx7rkSzrNeOlNM6jhDuYGI9z7hEc5A=,iv:Ckxo12efGOBPeJcI2fo+xEx+HeDLAt/dHXGmNmB0nBs=,tag:CuQcg6+Q5SYwU5tAAmekhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
