apiVersion: ENC[AES256_GCM,data:plw=,iv:RzCOrZJNWbPbPDWu3zGbh87AvCXsq4e4HPhYVRf6WAY=,tag:5wLBmYM6Paicohgs4yxwxA==,type:str]
kind: ENC[AES256_GCM,data:uR8zPE1N,iv:FFpo3wWoxA3a2pirCSQGHyCmiVRxJ01lzo/PH++zeBY=,tag:rgjJi9zcg1Yl7zMJOCFWvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SVdsARFaoKkhprg0hNwYfA==,iv:x36IT+CP4ZYVrcS3mFk4PR3rrPlE9T5+mNTtJSONG68=,tag:6xcMH13dTzT+9G0o9D2Ybw==,type:str]
    namespace: ENC[AES256_GCM,data:W5/6/kjsoA==,iv:Q3yZbjiveeMKMIYQyPw2kHurI8agRFW4hyEM+72+44I=,tag:ELtJA4m2Hmbj143jXbmSqA==,type:str]
type: ENC[AES256_GCM,data:PSmsCa3s,iv:8/TXTkYIc6O4KrBt+hm4XzWhT7bS+II7yf9o2iqQwGY=,tag:+NVkb6iYWp9wiPR4JvIf9Q==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:1JJ16+9TTyJl+Q==,iv:TuDsEy2optnYYTCGAwDepXrANRfhFRNUh5/kyIrnR+Q=,tag:DQwv4JXkDOsJzuQixC5DiA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:84pEnYsWkA==,iv:jrknjDrAxbilMvhuZcPhxsitIa2/YbcxKtFo7Fh7OkQ=,tag:la2qREBN9OsYZpvdCO5qRw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:b8CZ7vd2,iv:KGlKHuoQxN2zv1c5j4SNo9eVwrEJHBguDmaSiylzuJE=,tag:Kk5uE/cihiqtNa6yP6a2GA==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT2JLRGdiRXNkRVpXZGJD
            enVMek9YSXZ0ZVBzdzVOUm1BMzZtbWtzWTJNCnZYS1NzSXpKWG5UbHZiZW90YWhv
            V1VEODY2K1FuVWlDSkl2RWVab0tTRFUKLS0tIC9uOVNZVno4SFhCY3g5cVdTWW8v
            MFhxKzl1SVBxd2R2V1RTQ21VVC8xR0EKkkqhQtf+sgZx5akqHcTsAWW1Nv0R5Za8
            OuZpnxeTHqDHs2gwcIw2Yr1imod+6/NnbBZjBZqkwbvHMgTbyQ+NyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:35Z"
    mac: ENC[AES256_GCM,data:bgXbPs06JF05P9uo5hbOf9OXT8e7ojF6dbTz4ESeIME5sitckGA+1AyfR0BbNJmsXzzhHuSs2caJzE7hiWUAN7imr5SeDRVvyiyf21yNufMwuvygkVpHUbk7L4Iv28SA21EFnAr0zkUAWwmvToUm4aOahgJhAF0IYq5UOVvYaoY=,iv:GmtJW1ItQFBfm2LegPw9rKDYh7/ikOl01uT89hVN7f4=,tag:pWdQj2IRPZjTc8EAhVduBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
