apiVersion: ENC[AES256_GCM,data:Lbc=,iv:wHoLkxVYc0fuBA5Ohy3I9YWDl74wQaXZTnX5uKkcY0Q=,tag:qFrwi/VBxqwGZsJKDjoOag==,type:str]
kind: ENC[AES256_GCM,data:5Hm/7j6D,iv:8ADvC3sguEHYVhjO0uNxGhpefYJg9XeeUCb3My9Aqtg=,tag:DEoHib8SzNkEAHS+QeyAAg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U8vd1ZfNIjRFiZguzKhkTQ==,iv:p7CHryNTKXovvog+O29gulLvS4T6RlD9hKrAh8oOE4E=,tag:VeuLCtyl3twBEj3vc2eK9Q==,type:str]
    namespace: ENC[AES256_GCM,data:oZGYPj1VdA==,iv:XfGyyPKbfCiuhg4PMO53LJGF0X9B7SHbjsTepqnHv44=,tag:sjaVniCJlHe53ww2Uj51vg==,type:str]
type: ENC[AES256_GCM,data:2ZLOwsBL,iv:jYsT5ee7h+hUedj+br74+vDnIWti4wgN6NiXjtA+h/Q=,tag:djQS4DMCYkPXNVOAYKRaYA==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:9YWGwvNo4kSwLg==,iv:oNj4Ur6QY9jwVGZ3vrYZmSlgzuLPNSY9e3SHXCl3MbI=,tag:e/r0BFJm5J/S0XA6Sq2K7g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:W0YDgcEKZw==,iv:tyCzGYn5QKluHM7PI3Osg/GKbtDKIIEB3+jb6n18BaM=,tag:1XAmxmzQBKd8vu98ZWgN2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Z/GigxC/,iv:J7F1cemt5AZPjHcsah1pLt6sIxCL917h4QxYCpxbPOk=,tag:5+DyqCGFwQNZEeuOuOgeVQ==,type:str]
sops:
    age:
        - recipient: age1vxtgy82n4vprjft3pp34hnwcneu6ltf5fe2k0xwzxuddf3w8ksss8xw830
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVFNESVZRL0I2Mk5OUEl6
            MzBGTVE2ZUU0S3o4bHZxWEx0alZwMDlPZFM4CldjK2poekdMOHVXRjk1L3VzbGRJ
            cGZnQ1NSUXl3NkJiQW83eG54WjhpajQKLS0tIDZjRHhuMlFLTnlwV21VYVMrSFZG
            V1Fzd2RiYzBJL2lweW4vbHdZWElOdncKm0bFBPxrO7SPLfiS8/+hXHYvQGBV9TrR
            cUMpo4ttQKNE6yHY4aROqEwJBSrVd6Adkhbssn+uF9J+hETGd9hIAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15guk5yt7drtwmfl7uu3x03snfmtd2zdkk7lnay9tng03kzce8gqq63hw6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eXNZTDI5QVFNaENXL2JW
            c3JQSUZYbXhveTN6UVpUT09sd0VnOGRaekZ3CmlEZklIWjhuTE5LbjFXejJNcENW
            aDhETGZVVHpwbnZwMi9IbWpzdTZGTFUKLS0tIHFBcjl1MlFqc1JJc0MxalBiSW15
            YTBDRGRyenl6dWUwNzhXMTBod1ZqYkEKTeIKn3YdJCnlxJcEfLtNmgjjlqpVv/xG
            /1X/WBFVkbM72pHnX67vyI9162FlGIYpb6xcr4qkbVT6hzZbx0t/kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T08:40:12Z"
    mac: ENC[AES256_GCM,data:IZx3osl4PAGM4JR7gNcl3iwdx8AzcyM1b1IUNJr4vjfpg1yPeyEhZWhQnk8uY7qYTtK2XZzOfEDaaZfoMlsDL+ECQ4Vv7wefdDwT3WozZ7f8Gr9BB+zqvaD5k0O8SwSGB4xfx4SRn0sq0jekl5xhMu7hZV5FYz0AyqLCgK04/Hg=,iv:KzRKRwCdMZxQZNtVnLLKPhRFKk9ZPekxqXRyU/zWkPM=,tag:RP7FZF5lQHNKEHpQKK+HKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
