apiVersion: ENC[AES256_GCM,data:oCI=,iv:+xyAhjeXsOCoxbaovQYP/W/6ZbGyrwRDn8egn10kxtU=,tag:7zClCdn2XKEt4xB8b9WBSQ==,type:str]
kind: ENC[AES256_GCM,data:rwf92401,iv:rhvjF0rebMBGjIJfa8iCpMDJM/a25WGl/Qbj8JR+YSI=,tag:dSh7vz+mLhBydgh5WpkhkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ydoE4KBn1pm91zWCtw==,iv:D0lguijjE3M0RuswLZiINHKaDy4NPbLyzno4TC6uzfw=,tag:470P0JRCfftC1Lk6U9Bb6g==,type:str]
    namespace: ENC[AES256_GCM,data:6xxA10XgZg==,iv:L2z7Qgt7y9ao4hCiGl2JGB5YmSN/6MAk5btQHf75QkY=,tag:cQ1dsbJ5VdymKv3N0butAA==,type:str]
type: ENC[AES256_GCM,data:unSayOJH,iv:dj386GP5rjHH2pWZcUju0ecp84UqtACGlz1FNhZZCgo=,tag:MhWLTo2Tdj/Ow3kdJ7UbbQ==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:G+ZZW0hIfyDf+hBNR/LXy0FG6cRwHVGK81ZMn5loekM=,iv:LCTQY5bxBJ7KBfErvgkPM22mS+oX2ASmlIM7Hs8LkSk=,tag:K8zsC/0w1jMgvIh3c/fREw==,type:str]
sops:
    age:
        - recipient: age1vxtgy82n4vprjft3pp34hnwcneu6ltf5fe2k0xwzxuddf3w8ksss8xw830
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeU1Qa0orN0d1SE1kZVQ3
            K2VLTldTUDNhVjJiNDZ6NkZGa0piekdvR1F3CkJ3OXdZWXovRnk2Z2xoQTFFR2RX
            QVRqcHNUNVE5cW5DdGJJMC9LVzFxVXMKLS0tIHF5aDY4NmtYUTNqbEJwNnR0eWta
            QTBCV3JtWStLQTZlMnIzeFNRYi80NFkKyn2P1kBKcmfX8ToOtKMSAw8MZYmyHdSA
            cDDNrKzHnAbyQuzhjYxijJuoZShhGjxtaqYchbKN11Ogj9WzRm+DQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15guk5yt7drtwmfl7uu3x03snfmtd2zdkk7lnay9tng03kzce8gqq63hw6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR2k0KzlvUmRudDBlazRo
            R2gzTktEWE9xOWhhNjVuMmRDRTU4UHdlU3hBCjNENVN2U0dNNWxJNEFjVEVSZk1K
            VU9ObzBKdXNMZDNFeG9ZS1Jtc1BxSEUKLS0tIFBZRTRwU094M1hBWWs5cHNWdkhH
            ZG91ZGpGeG96QW5LelVSaUdMb1FIcDQKaLJPF7lJDwb7zJ6BNup6k1WOg9lJuqnA
            7BsCn06Cs++riOJUsUzVVJA+m5M+rgFcxYF2tvtgbW74cDNtRYiBAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T08:40:12Z"
    mac: ENC[AES256_GCM,data:QcklCsbu5/Ld8/XrDNz1TeQ/8NvWd2HN0vgIzFXztvsqPUt3luTWu7ftBl369dvgFADtj1TQ2eRc9YClLHaHoZ/+jz7UuknU/PnUhwENU2gR18wxJgzobp4gT2qLN2yXrqMaP4zO+gC1kP6VD3YmtRW0Gj6gKgVeX1wS6IFq/7w=,iv:mNYF6Nr3KnWUAIJBA/b/FzlkapFRFYeufIpyRiuFcns=,tag:aCiq6ZMnlQUxiNTbka1lcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
