apiVersion: ENC[AES256_GCM,data:ybM=,iv:fahDO/xgztdeYYPihxRJY4bppi00h3JCFZqob/tYDF8=,tag:wGeKo2SaORDM8oSmwowpnQ==,type:str]
kind: ENC[AES256_GCM,data:2dYvlAxy,iv:0yVThUCesBeRM1aeQYY+eFq5Ui/4hu4ZZU7mCqBbPdI=,tag:qkPdOw60fTG9jTPZ1phh0g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qujyaureADoElDsh2Q==,iv:rp0+HPXBO23fgPsc8msUDMfly3vHMlfkYHjoHvdp51M=,tag:j0vSA3FlrcJpmb2JnyxU4g==,type:str]
    namespace: ENC[AES256_GCM,data:uitMcAxmKA==,iv:9wpnyVm7xG6l2Ej8zyNmP/LrrG5lPOXjVOdCmktUopo=,tag:yN70qa/vz2afwGaO5XX0sg==,type:str]
type: ENC[AES256_GCM,data:4zmye7PC,iv:RLjMVhbROg3Mp5ATFcOXhGUiqW5hmqS36zwrWrQ74pI=,tag:7kDEw9bkKYsK5rHEx4CxvA==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:p8l3/tlTYXHk1Gybobi4TCKtLlgwfYZhS4d6bSPXmQc=,iv:fgxCTp7sBMXjpGo13xcvsb3TaALxEqP10UeAFMqGDEY=,tag:YmEodL5CPAdL0wQpt5NEtA==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OEdUN3hvRzQyYXhUOTdI
            Ny9JZDc2dDlkdnZDUnZTUEVRM2pneHl1N1UwCmlnaUQ3ZFJ5RkRnaEpIWkZiMXRG
            ZVU5ZlBVUWpvcXkvamV2c2FrUWZ0VHcKLS0tIDBaQTBPYTdxQWFSUXRyT3ROeU9W
            ZWVtMjE4cVJWWVpxM3Y5UmpzV01aYjgKKgZrtOjkc+4bhpN3z3gM/kla6jBsj1Bu
            SgW3w2V3zfuWFOwEcLUowPT6xvqPynLA4qvpKVal/M5USMR15TQhcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:35Z"
    mac: ENC[AES256_GCM,data:rbKgthS2kNoO5o2wjoaniiZMY1WcjwzxOhK6nxWyfAF2JJsy+8duCX6pw72eJoQ83wzNwTEVr1DSlKtZV+c8kvSZsVqovCQeREsCRaATIqfU2qYM9IfG2qJv8GR2onnLbAQxSQYxu9FlFSbPnVOKno2d2IW0EdQ9Cm0tXHiD6+o=,iv:SjTBJwLL5rT/m9lx8Art5Ocd04+OuUBwl4vTpq9du7s=,tag:KykopqqV0QfUhai3LBv+/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
