apiVersion: viaduct.ai/v1  # "이 .enc.yaml 파일들을 복호화해줘" -> secret generator
kind: ksops
metadata:
  name: secret-generator
files:
  - ./api-server-secrets.enc.yaml
  - ./postgres-secrets.enc.yaml
  - ./redis-secrets.enc.yaml
  - ./grafana-secrets.enc.yaml
