package domain.payment;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import vo.Money;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PaymentTest {

    @Test
    @DisplayName("펀딩 결제 생성 시 PAID 상태와 GIFTIFY_CASH 수단으로 생성되어야 한다")
    void createPaidForFunding_ShouldCreatePaymentWithPaidStatus() {
        // given
        Long userId = 1L;
        Long fundingId = 100L;
        Money amount = Money.of(15000);

        // when
        Payment payment = Payment.createPaidForFunding(userId, fundingId, amount);

        // then

        // 1. 환불 가능해야 함 (PAID 상태이고 아직 환불 안 됨)
        assertThat(payment.isRefundable()).isTrue();

        // 2. 취소 불가능해야 함 (PENDING이 아니므로)
        assertThat(payment.isCancelable()).isFalse();
    }

    @Test
    @DisplayName("환불이 성공적으로 수행되어야 한다")
    void refund_ShouldSucceed_WhenStatusIsPaid() {
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));

        payment.refund();

        assertThat(payment.isRefundable()).isFalse(); // 이미 환불되었으므로 false
    }

    @Test
    @DisplayName("이미 환불된 결제를 다시 환불하려 하면 예외가 발생해야 한다")
    void refund_ShouldThrowException_WhenAlreadyRefunded() {
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));
        payment.refund(); // 1차 환불

        assertThatThrownBy(payment::refund)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("환불 불가능한 상태입니다");
    }

    @Test
    @DisplayName("완료된 펀딩 결제는 취소(Cancel)할 수 없다")
    void cancel_ShouldThrowException_WhenStatusIsPaid() {
        // given
        // createPaidForFunding은 PAID 상태로 생성됨
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));

        // when & then
        // Cancel은 PENDING 상태에서만 가능하므로 예외 발생해야 함
        assertThatThrownBy(payment::cancel)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("취소 불가능한 상태입니다");
    }

    @Test
    @DisplayName("펀딩 수령 확정(Settled) 이후에는 환불할 수 없다")
    void refund_ShouldFail_WhenPaymentIsSettled() {
        // given
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));

        // when: 선물 수령 처리
        payment.settle();

        // then: 환불 시도 시 예외 발생
        assertThatThrownBy(payment::refund)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("이미 수령 처리되어 환불할 수 없습니다");

        // 상태 확인
        assertThat(payment.isRefundable()).isFalse();
    }

    @Test
    @DisplayName("PAID 상태의 결제는 수령 확정(SETTLED)할 수 있다")
    void settle_ShouldSucceed_WhenStatusIsPaid() {
        // given
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));

        // when
        payment.settle();

        // then
        assertThat(payment.isRefundable()).isFalse(); // SETTLED 상태이므로 환불 불가
        assertThat(payment.isCancelable()).isFalse(); // SETTLED 상태이므로 취소 불가
    }

    @Test
    @DisplayName("PAID 상태의 결제는 다시 완료 처리할 수 없다")
    void markAsPaid_ShouldThrowException_WhenStatusIsPaid() {
        // given
        Payment payment = Payment.createPaidForFunding(1L, 100L, Money.of(10000));

        // when & then
        assertThatThrownBy(() -> payment.markAsPaid("PG_TX_123"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("결제 대기(PENDING) 상태에서만 완료 처리할 수 있습니다");
    }

    @Test
    @DisplayName("빌더로 생성 시 createdAt이 설정되지 않으면 자동으로 현재 시간이 할당되어야 한다")
    void builder_ShouldCreatePayment_WithDefaultCreatedAt() {
        Payment payment = Payment.builder()
                .userId(1L)
                .type(PaymentType.FUNDING)
                .status(PaymentStatus.PENDING)
                .amount(Money.of(1000))
                .fundingId(10L)
                .method(PaymentMethod.GIFTIFY_CASH)
                .build();

        assertThat(payment.getCreatedAt())
                .as("createdAt should be auto-generated by builder. Payment state: %s", payment)
                .isNotNull();
        assertThat(payment.getUserId()).isEqualTo(1L);
        assertThat(payment.getAmount()).isEqualTo(Money.of(1000));
    }

    @Test
    @DisplayName("withId는 기존 필드를 유지한 채 ID가 할당된 새로운 객체를 반환해야 한다 (불변성 검증)")
    void withId_ShouldReturnNewInstance_WithSameFieldsAndNewId() {
        // given
        Payment original = Payment.createPaidForFunding(1L, 100L, Money.of(20000));
        Long newId = 999L;

        // when
        Payment withIdPayment = original.withId(newId);

        // then
        // 1. 서로 다른 인스턴스여야 함
        assertThat(withIdPayment).isNotSameAs(original);

        // 2. ID가 설정되어야 함
        assertThat(withIdPayment.getPaymentId()).isEqualTo(newId);

        // 3. 기존 필드들이 동일해야 함
        assertThat(withIdPayment.getUserId()).isEqualTo(original.getUserId());
        assertThat(withIdPayment.getAmount()).isEqualTo(original.getAmount());
        assertThat(withIdPayment.getCreatedAt()).isEqualTo(original.getCreatedAt()); // 중요: 생성 시간 유지
        assertThat(withIdPayment.getStatus()).isEqualTo(original.getStatus());

        // 4. 원본 객체는 ID가 없어야 함 (불변성)
        assertThat(original.getPaymentId()).isNull();
    }

    @Test
    @DisplayName("빌더로 모든 필드를 명시적으로 설정할 수 있어야 한다")
    void builder_ShouldSetAllFieldsCorrectly() {
        // given
        java.time.LocalDateTime now = java.time.LocalDateTime.now();

        // when
        Payment payment = Payment.builder()
                .paymentId(1L)
                .userId(2L)
                .type(PaymentType.FUNDING)
                .status(PaymentStatus.PAID)
                .amount(Money.of(5000))
                .fundingId(100L)
                .pgTransactionId("PG_KEY")
                .method(PaymentMethod.GIFTIFY_CASH)
                .createdAt(now)
                .paidAt(now)
                .build();

        // then
        assertThat(payment.getPaymentId()).isEqualTo(1L);
        assertThat(payment.getUserId()).isEqualTo(2L);
        assertThat(payment.getCreatedAt()).isEqualTo(now);
        assertThat(payment.getPgTransactionId()).isEqualTo("PG_KEY");
    }
}
