/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

// Type-safe project accessor 활성화
// 이렇게 쓸 수 있게 해줍니다:
// implementation(projects.bcShared)  // Type-safe!
// 아래와 같은 String 모듈 이름 참조 방식 대신에:
// implementation(project(":bc-shared"))  // String 방식

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "giftify-be"


// =============================================================================
// 1. Business Capabilities (핵심 비즈니스 모듈) - 계층적 구조
// =============================================================================
include(
    "bc",                   // BC 부모 모듈
    "bc:shared",            // Shared Kernel
    "bc:member",
    "bc:auth",
    "bc:funding"            // Funding 모듈
)

// Payment 모듈 - Hexagonal Architecture (bc 하위의 중첩 구조)
include(
    "bc:money",   // money 부모 모듈
    "bc:money:core",
    "bc:money:application",
    "bc:money:adapter"
)

// 물리적 디렉토리 경로 매핑
project(":bc").projectDir = file("bc")
project(":bc:shared").projectDir = file("bc/shared")
project(":bc:member").projectDir = file("bc/member")
project(":bc:auth").projectDir = file("bc/auth")
project(":bc:funding").projectDir = file("bc/funding")

// money 계층적 매핑
project(":bc:money").projectDir = file("bc/money")
project(":bc:money:core").projectDir = file("bc/money/core")
project(":bc:money:application").projectDir = file("bc/money/application")
project(":bc:money:adapter").projectDir = file("bc/money/adapter")

// =============================================================================
// 2. Support Modules (공통 인프라 지원)
// =============================================================================
include(
    "support",
    "support:common",
    "support:logging",
    "support:security",
    "support:web",
    "support:jpa"
)

project(":support").projectDir = file("support")
project(":support:common").projectDir = file("support/common")
project(":support:logging").projectDir = file("support/logging")
project(":support:security").projectDir = file("support/security")
project(":support:web").projectDir = file("support/web")
project(":support:jpa").projectDir = file("support/jpa")

// =============================================================================
// 3. Bootstrap (애플리케이션 진입점)
// =============================================================================
include(
    "bootstrap",            // Bootstrap 부모 모듈
    "bootstrap:api-server"
)

project(":bootstrap").projectDir = file("bootstrap")
project(":bootstrap:api-server").projectDir = file("bootstrap/api-server")
