apiVersion: ENC[AES256_GCM,data:2VY=,iv:vjZ4leZhk+VyUgNC8XooIo8bINDy4IYIIByVmHE3nIQ=,tag:nkuaWZi2+yaNouqdZkcEgQ==,type:str]
kind: ENC[AES256_GCM,data:lY14QU2T,iv:OjrWiMm4svTN2i5uyTw14cPbHVUTzLoEtMZzS/dJI9s=,tag:Ez8bjzSVjBUOQeR3Ql25yQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+JcrfQ/7Ran63ESY859qdUDJ,iv:+sQu4He0lluoRZJyXYBpePoCwVKZuiCF1SIq+xibZM4=,tag:1/9SsgJcMDSzdcu6xBOkMg==,type:str]
    namespace: ENC[AES256_GCM,data:s+mfMLCi2A==,iv:ZtYxeqeBgnNwuOybdJVI2qoTsZmTsdxPoAE2SccRuRw=,tag:8MA+I46lF2HpP3RRBL3Awg==,type:str]
type: ENC[AES256_GCM,data:PMaka5QF,iv:XgISlVVx/t4uE2pswoxhhGKg4BnasfRsX9ohZdPFmZU=,tag:gzZ1a10fkdRitgzVs7+yCA==,type:str]
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:tbmTGQ9oITbRjp056Qqan30QuJ3DFjV97POXR184YfL49u3Bz97nFLdUc/CcXiCQ7EaC04at+MnASI1aI1wMx/6nVV20lFEhY0J2b96sit5cNFT735v/TPSCNCJPp3F5GSPz9BjVZ6wa0Tn3v40YD4u97cTyXoaDVgewklsOrgZTlP/DmOAEDUvt/ncVVJDMVZ6oMPqm+5O8JFPVZZLsao+8hTqgwOArqth1bl8S6MgqndgBIiok2w==,iv:EzKSagQmqjI3mCdWJZXJYHQC2TP6FQ1urq7oRraSgyc=,tag:FfKP9OyGN4yE6BYMrTUxxg==,type:str]
sops:
    age:
        - recipient: age1vxtgy82n4vprjft3pp34hnwcneu6ltf5fe2k0xwzxuddf3w8ksss8xw830
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Uk83R0s0dkE4NFhYVXNF
            cU42M0pqanRTZE9GTDQyWVpCM3dDOWN3Q1U4CjJsUkxYY00wMmRBc25aWDcxWHdl
            cWRQMEV1Ykh1aTM2WmNmNVE4d1JXbGsKLS0tIDlxdnRhL3dOdU8xNlNYd3hyeitU
            T1UveWl3VUVFcVE5UWl3MTV6ck4ybEkKoD1SBkvBiM5yU+d5SPmDLdXPnFOqfp7e
            jHkDNduiWbBGo9AG0GzoI+PU4UxCoJtX18/DskGSqpUCUhrDoscz8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15guk5yt7drtwmfl7uu3x03snfmtd2zdkk7lnay9tng03kzce8gqq63hw6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcEg5ZVNFYllzMUJIRWFa
            cUZjNnR5M2RHem9BV09JQmlrTS94QjFZUm4wCkFGaDR3R2pXOW1ad1ZNVWdSVGl3
            R3UxYUVpazJKTnNqRzlxV0QrVE42cVkKLS0tIHlTenVpc3BpVGM4T1VQTEdWd3g5
            R2VvdXhvQTRZUnlDWXVjM013amdDdDQKbBSPPbaQj6rmkzuiLFZhOE3eefbL+FdT
            bXhYuHvvD7IUeoQyWOgthiDmOWM8Zcc9mkEdtZPeL5YzQlhfG13BgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T06:13:05Z"
    mac: ENC[AES256_GCM,data:JHQwPHqxN4+ReF2yRe/QCXkW1c3oiLRiE52DYKFnA3iHFGOaMEUNDnQdVOOrAjGdRLdTSBh34MFKnG71tdpfbPh60DJuY7dvGz/M6yt94vr7beuc6SkIy7A1wwrhHirQ45tpHcTB93wX0pd8JRIGpCNuxNjun7mCeCyNhfWG1IM=,iv:onLzSCq4uigoOR13A2PfBkcPbL4r8l/xZ68h9kB19M4=,tag:s95SngUFQGrcu4ffY+xZ7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
