apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ../prod/api-server-secrets.enc.yaml
  - ../prod/postgres-secrets.enc.yaml
  - ../prod/redis-secrets.enc.yaml
  - ../prod/grafana-secrets.enc.yaml
