apiVersion: ENC[AES256_GCM,data:DTc=,iv:xkeqgUh4Gvr0j1TgppZSUsOwCidqbfadhWEFS7TuU2Y=,tag:EIqNqFf61fD4MPU7zjUIdg==,type:str]
kind: ENC[AES256_GCM,data:5invykai,iv:r0XGHn6oBxQPI+ymqxnNWkHOrK0vTPvocGbvHoamHG4=,tag:hgsQXII2Emom/ptJfPdEbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5+GHpIyAUQKpRLblYg8gZkh8,iv:QLV97cLoHf1GZvqzAOlkbEzXIdwWED4SZvTiWGcScPs=,tag:UWJNsov921+cKNx1TXLRQA==,type:str]
    namespace: ENC[AES256_GCM,data:kmnCUpj5YQ==,iv:t/WJx2H9XME9EMunw0zr6Lc64Zswnva1LXxFQwHdSGc=,tag:bhLIHJV5Qq0IwH8bEV2HKA==,type:str]
type: ENC[AES256_GCM,data:LipkOg6b,iv:V0qOnktkPwCbnRr1OMDnZa7UROUhz4uzXuugNG85M4g=,tag:mEGuuZajWQcvKG1Ckf84pw==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:jiQIZacH,iv:JPpphaKy+PZtmCPfcwg+BlWHGCu9y0dcRtUAlGW83H8=,tag:GGznJ3PysC1iKq2V1XhZfA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:gUIP1u3+cBxywVAxSquIdYXLBl0LqPFrAdiHlTvh9hU=,iv:See4MI4SS57BXv6/e5K5Ovm3c0YXkoBPNUi3r/Okfv4=,tag:0UDCjIVw6EKphG428mkf3g==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:j9mI0SnvtQMw1KykEgqPMCZuTDiIJsGvkOOkpEj1WgQ=,iv:ICXfFBXCg+cc9BosX0FSenqwvTfdgd/u2Mw8mwhHkzI=,tag:dzqeWm+hfCzhyHNJEwIzgQ==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:2SJan4NUPl6XVbwIJlZYRFreGEbOpOMRv7616WRQdBuCTui2mzjRbdvGhFp2cktefbmQlZBbOd1edUf9gMr+lQ==,iv:Av2OVOcM5JOfyZzZWxZ1KIVS/tV3FawiZCCNdU8XmLw=,tag:LfXO3SgIP4/OioXifw5sCQ==,type:str]
    TOSSPAYMENTS_SECRET_KEY: ENC[AES256_GCM,data:3rZMw1egAaJqj+eExl9yMfR58i4/F9xzVJKt14If21j9p7Ve,iv:PEeGDW4eU+9Pja+Z+w5phRATtHJoEVBEKPrsrIbBxTM=,tag:nOf/KUOrPl1H8zux2eyD5A==,type:str]
    PAYMENT_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:zYqDe8kdQ8WkE9ZZPxUiOvb5ldcWNvecDptDW+9ETj4=,iv:J3Evcnw+38efuws/We+6W7AkAdWuXpYaEpmVwXpUrTQ=,tag:FxuIhXXy+FcOWDbfdRIK3g==,type:str]
    PAYMENT_ENCRYPTION_SALT: ENC[AES256_GCM,data:Tl0pVSmMxEbts9fC0QP6KChNZ6wVr6vizRF5Q/jNpUA=,iv:BmsztdOuIR3tNfJYkUapGF5Ek2z2gaWz4wVH6yAJHoc=,tag:CEi4BdlQBTDx3RyuPMX/yA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:gOGlm/pKtpkxrw==,iv:HttTrCLZPF9VIJXMwUPmhJ9SV6zrO5JBz0fSZANZfzc=,tag:vvtUsNVtR/j2Xn1KJSTC1w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:CjVwrmLNXNMEcg==,iv:lfcPQTNCcAmzKvc5n+18UALATH3zumQFqcrujN1Gun8=,tag:ANHvQHTvZXg5T1NXybEsJQ==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MUs5R01lN0drTnBZVmpF
            VEN0cmoxd3k1YmQ5QVBsZVdVdWdVbFRFZWowCkU3aTc5SjBQcHVQcFg4UFRaQ1gw
            K2FzdGtuTUlkMjFDdlpTQm85Y2xKdUUKLS0tIDdQTkdmcnhnc2VnV0xYcGpmYTZK
            dE15b0ExNHVNRkVLWVlySXRRcytCMG8KYZ5MMM+d1RZsuyQtBvwn41nOffJHkrZD
            CfvITQfXlCzwa4kxwSf8cg01Bf2B0ri4LHp88rTBIIMLxj9sJ+6QXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:31Z"
    mac: ENC[AES256_GCM,data:dKhcFx0b7CtOZrlbN2ncBUIJ621PTow+A3CZ3f1p8LaKbFU0SHdy4OLQ+WeQA29NjGA7f97Q34kePq5SjSg7k917H2JsADvL5MOQbUbh2uf53mNDo1VTuDXoT1m3C4JYRDjiP+pvURWkt5f1pLAzd3PEiSXF41Oh6UvWQWoG5yk=,iv:RtQ8ThGdIZ5qC5irN5hrgtE7uY+J864RNjiG3Y5AlLQ=,tag:/8xuiXxWnW5wGSfzqUV0xQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
