apiVersion: ENC[AES256_GCM,data:zJg=,iv:YD98U25JmXk7J/+TnTRoSpRsRc91/fruDRDnps4mnrk=,tag:aWdilLBf2CxW9W8aiK0Dzw==,type:str]
kind: ENC[AES256_GCM,data:yLLEoaJk,iv:FPoDA2JZlUVK9Bo9Ss9EyeuqTSPKrgcDG01DaqgNWgk=,tag:gz/s7cizCwnMKUIX+Uluww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fhrqOjFtn0wS1EMw3tf1,iv:B9CuFY08ExQsMipZq53ZMsX26p+YqZM7PHXRF/G/BIc=,tag:DeXyluOg2/qpaA8mWOkNAg==,type:str]
    namespace: ENC[AES256_GCM,data:QchObpd8qg==,iv:Kq4ZakBZKW0jXxzqTAnUQczkHWLKrZtw4CSDApZiLHE=,tag:kyt+epCevzhWLBwRqUuiIw==,type:str]
type: ENC[AES256_GCM,data:RTZEbft7,iv:m9SpNrTjK1qjSaz6kWBr7TjyylWvksqbbxIK+dysfpo=,tag:QITpQZB6NHW5PU7mEvHnzw==,type:str]
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:dYxEiJYCzEv7hCrcsBNWOw==,iv:Qi70hxvp+m+tlN9yZrFiS/0TkaBwxzY6KgAtmu1y6N0=,tag:HCUDZvysrMfrGCAskJPwmQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:xHWme922d89gjsqFqdsJtg==,iv:a5EE8my2tNQal9YEbhlfoLYnikVV5ApreISZg/+FHA4=,tag:jHen4HI5TjwtefHeCK+hpA==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWXBtelM4clM0OVRoa1ND
            cStFTWI1WTl5VldNYUlMQlFSQzhVMFlLTVNFCjJHTXEvVXJPRis0QUZNUURHNHVC
            NXF0S0VVUWtMSUhrZ283cVN0aHNGbGsKLS0tIHl1VTQ4VVlkM1FtWlhoUkxIb3J6
            c3BTYnBqRHpOV0FXRVhybUdYQzhNejQKkq45UaWzg4OoSlf0wIvn3rdMot8d/sCm
            DPrSGohT/qT+T+EnEPsylPoQ464Hw2i4QdkqIfheup7DkuC7ASvsfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:31Z"
    mac: ENC[AES256_GCM,data:UJlNHs6C+ummUyUtFxqviJXGhpt5rzBTAWiu4wnioJagcPY1wnRx4XJc04yX1P1GjmrFEavDLNFYOMipM8v/z8ThPLKKSEdD/IRBfzMqj78ZT94dPOl5BcE4I1yzSyi1d5NEQBkFOML7nKIpX874FqIHm05uKgT3gLeMxlKwk/k=,iv:UvPYvVGHgr3PIzontrEmHdxzprojmChmW3eQ2PiXWYc=,tag:7spbvJVMvdp2rYTVAssymA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
