apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generators:
  - ./secret-generator.yaml  # "이 .enc.yaml 파일들을 복호화해줘" -> secret generator

images:
  - name: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_team201_be/api-server
    newName: giftify-api-server
    newTag: local
  - name: giftify-elasticsearch
    newName: giftify-elasticsearch
    newTag: local

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-server
      spec:
        template:
          spec:
            imagePullSecrets: [ ]
            containers:
              - name: api-server
                imagePullPolicy: Never
                env:
                  - name: SPRING_SQL_INIT_MODE
                    value: "never"
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "200m"
                  limits:
                    memory: "768Mi"
                    cpu: "500m"
                startupProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  failureThreshold: 60
                readinessProbe:
                  initialDelaySeconds: 5
                livenessProbe:
                  initialDelaySeconds: 10
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflared
      spec:
        replicas: 0
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: elasticsearch
      spec:
        template:
          spec:
            containers:
              - name: elasticsearch
                imagePullPolicy: Never
