apiVersion: ENC[AES256_GCM,data:o0A=,iv:rSBhF8kG+sPnFxjedih+/5tYo3e/yZgNX3Zh4iw0Fdw=,tag:PHMj4tMRRREpenCOtZOhwA==,type:str]
kind: ENC[AES256_GCM,data:Cr7ZuWyZ,iv:pTrbsPyrUgMGWwRvLgDtS7ZaGdY/yXKMEn2Ei1uJGR0=,tag:UEbDhuNWkswf+Rl4pQtb5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EAfSi/63Uu3M9ltEJJfpww==,iv:0oSrq9wR+sIWG088Kd+YiVzfbh4bXm8LI9kPTuVOMTI=,tag:cU/h3ZfmQo7FILxe9MRZqw==,type:str]
    namespace: ENC[AES256_GCM,data:B5v3nJLpxg==,iv:iJS2NGIs2TirtAaEVKnvXrkH71fvlPWs61CYQ69lQgQ=,tag:qNJlCWyI1vx9cJicNI2aVw==,type:str]
type: ENC[AES256_GCM,data:Lir7j6js,iv:ZgVjH5hA0frw12enWGxMET5DbrCPdQbtNqUnuPTad54=,tag:r64/mUSkkKVneadZzYViwg==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:e7zj4flZZLcVQw==,iv:HunC/w64KGIokZU4NSElJCugdSE2t2FfU/TRpS0d5vM=,tag:55Z9Jgu5+gYXvzVGNb7KDw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:KI+4ByHXjQ==,iv:rYbSTCwWwCf+E2zTazjz9/znLhrH2V3Ds166gByPtBM=,tag:QyAyQ2lWNPoVIy2oPhrc2w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5fAc0R//,iv:h3gn5JDWKpOe0ikTsso1bvbEvkPW+vX0pWdh8Dld5zY=,tag:OHexTLw5tMWXzEs6hJmEtg==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU3V4WUdwbTh2NitlM1ZF
            QktPVXV5STVNeVY3K0xsRDdsUkhzVm00V1FBCjhGck9pRWVXSnJld1dCdUMyZ1FW
            OHIwSjRJa0lWMW1jbWpWTlNZakJUUm8KLS0tIEoxZzE1bmI0VFFkdXVPK3FwL1Qr
            L3FFcXFhbi9RU3Z5dFJRSGVQekprL28KTMPVq1/VBt7I5hs2WEBgdj1+xBgV/Tt6
            ZltWYMnSFp5maPPVxIaPk8ouFl7StDz6g6env3Vz2WE7q/lx8XJeoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:31Z"
    mac: ENC[AES256_GCM,data:6x0r6jXdLAQUQjwTU/u8tOEqtoeCBh+qCqdkup+CrFe2sqcF69ftpa3bu9JO9TlfIHQfp5qgv9TRMf9+araV9JdB5JAlr1qOcW1I8jKpyPjfrX8/N9lr1SUi9JidQqGlzxUR/Zex/9cyifQeBEm8J91hK1e9lC1WAxLjHuzQ6gY=,iv:wqFSNe3RdqAM+qZMAimQHfNYx9xVhdNSwbzj8V9/AMQ=,tag:dEQM1Xia6B3ACYMGck+S+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
