apiVersion: ENC[AES256_GCM,data:6Jk=,iv:hsEqGsrd5XWcsvmuMpsfGLzQwO0KyT2nun6nfk5i3xo=,tag:wF+Gm72Vwfx9jkZ0VosJeQ==,type:str]
kind: ENC[AES256_GCM,data:ThIxuOut,iv:JzcZqCj19NfGMdd1cUD+XYGdH75SJ5WMF3NOwj74New=,tag:VguSOhKQZPIsuzxub/Xy0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:02XiXiCy9rHM48hGyw==,iv:4QEFtPLuQvtDqZTGulTWLsfIbE2CjPrjNJeOEmyQ/rE=,tag:IKikRlmQOEm/q/ejIl5ptw==,type:str]
    namespace: ENC[AES256_GCM,data:Ensx2ir7XQ==,iv:6biTfgS6XxZJtU11iC9+Ar1kf770DQQoIyMI/T5Gyhw=,tag:/9W75yMsZVjsVGBoiU+Ojg==,type:str]
type: ENC[AES256_GCM,data:Rezsx4F+,iv:jRWwmFwc+3OBCO8y+T1BqKN6RN03rEdLgJ/QURVpFZE=,tag:pGD1nSX52JBO52seo+D+dQ==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:aGyF2kuV1Le+6IOv6UGIQVxUAZ6/vq/CgO8oveVUHFw=,iv:d/sKEFKyIrwAtpPBIv3xp6dHkp7bthu9wQu4NHskOdg=,tag:sbyy7fhz49tmwzasvtuCmQ==,type:str]
sops:
    age:
        - recipient: age1f0utknkpm97442amhksw87jrxd9nmkflqcv6dpek4aml63kh4ckszpy5yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWpxcWpGWTRrcmhEd01j
            VjFZOXlib1FCMTl3VWM4Q21GWElhVXpVczBZCk1zMTZUeCtUczdFMXVIUklPWXpV
            YWxMYnRVb2V1cnJNUURxelh0Qnp0MXMKLS0tIGhseEE4aVJOc3ZvTktTWXhJenQ3
            em1taHhhNElvdWJ5ak0rR2lsb3Y4QU0Kb/50zpWcv1eDj5bOP37XF6QeMC2ZKI+c
            wMONEkEAha1E6RXGMJ05jxBFnPxHpJxNDHhP0w+EQXQr293xkvfn1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:19:31Z"
    mac: ENC[AES256_GCM,data:rytYYlbA3J8fZY4lTas13pAUC4ugPTCHfwlTVmTykDS/Gexuae7r2WMuOp4WPtNJFzZtuCS+/F7+GcNS11QHrdrHGl5edwvlEP0t40thiGG5wdpUneO0cfKE+yJ+cW4Lj/z77c2rwKOJHx4HsFGATkLhhe1SBSieCg11GbmrY8c=,iv:p6EVicEilAEeBSZl0AIN3tYcnD4xkJFcXJjKpZnFftg=,tag:d8wH8SgQOu9UZiPff/dAOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
