create table members (
    birthday date,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    nickname varchar(100) not null,
    address varchar(255),
    auth_sub varchar(255) unique,
    created_by varchar(255),
    email varchar(255) not null unique,
    name varchar(255),
    phone_num varchar(255),
    role varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);
