create table payments (
    origin_amount numeric(19,2) not null,
    paid_amount numeric(19,2) not null,
    refunded_amount numeric(19,2) not null,
    version bigint not null default 0,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    order_id bigint,
    paid_at timestamp(6),
    updated_at timestamp(6) not null,
    method varchar(50) not null,
    status varchar(50) not null,
    type varchar(50) not null,
    approve_code varchar(255),
    created_by varchar(255),
    last_transaction_key varchar(255),
    order_items_json TEXT not null,
    order_number varchar(255) not null,
    payment_key varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table payment_histories (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    payment_id bigint not null,
    updated_at timestamp(6) not null,
    event_type varchar(50) not null,
    created_by varchar(255),
    history_key varchar(255) not null unique,
    metadata TEXT,
    updated_by varchar(255),
    primary key (id)
);

create table payment_cancels (
    cancel_amount numeric(19,2) not null,
    canceled_at timestamp(6) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    payment_id bigint not null,
    updated_at timestamp(6) not null,
    cancel_reason varchar(500) not null,
    created_by varchar(255),
    transaction_key varchar(255) not null unique,
    updated_by varchar(255),
    primary key (id),
    constraint fk_payment_cancels_payments foreign key (payment_id) references payments(id)
);

create index idx_payment_cancels_payment_id on payment_cancels(payment_id);
