spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: settlement

server:
  port: 8081
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    app.giftify: DEBUG
