package app.giftify.friendship.domain.event;

import static org.assertj.core.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class FriendshipEventTest {

    private static final Long FRIENDSHIP_ID = 1L;
    private static final Long REQUESTER_ID = 10L;
    private static final Long RECEIVER_ID = 20L;

    @Nested
    @DisplayName("FriendshipRequestSentEvent")
    class RequestSentEvent {

        @Test
        @DisplayName("생성 시 getter로 모든 필드 조회 가능")
        void getters_ReturnCorrectValues() {
            FriendshipRequestSentEvent event = new FriendshipRequestSentEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            assertThat(event.getFriendshipId()).isEqualTo(FRIENDSHIP_ID);
            assertThat(event.getRequesterId()).isEqualTo(REQUESTER_ID);
            assertThat(event.getReceiverId()).isEqualTo(RECEIVER_ID);
        }

        @Test
        @DisplayName("BaseDomainEvent의 eventId와 occurredAt 자동 생성")
        void baseDomainEvent_AutoGeneratedFields() {
            FriendshipRequestSentEvent event = new FriendshipRequestSentEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            assertThat(event.getEventId()).isNotNull();
            assertThat(event.getOccurredAt()).isNotNull();
        }

        @Test
        @DisplayName("두 이벤트의 eventId는 서로 다름")
        void twoEvents_HaveDifferentEventIds() {
            FriendshipRequestSentEvent event1 = new FriendshipRequestSentEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);
            FriendshipRequestSentEvent event2 = new FriendshipRequestSentEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            assertThat(event1.getEventId()).isNotEqualTo(event2.getEventId());
        }

        @Test
        @DisplayName("toString에 모든 필드 포함")
        void toString_ContainsAllFields() {
            FriendshipRequestSentEvent event = new FriendshipRequestSentEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            String result = event.toString();
            assertThat(result).contains("FriendshipRequestSentEvent");
            assertThat(result).contains(FRIENDSHIP_ID.toString());
            assertThat(result).contains(REQUESTER_ID.toString());
            assertThat(result).contains(RECEIVER_ID.toString());
        }
    }

    @Nested
    @DisplayName("FriendshipAcceptedEvent")
    class AcceptedEvent {

        @Test
        @DisplayName("생성 시 getter로 모든 필드 조회 가능")
        void getters_ReturnCorrectValues() {
            FriendshipAcceptedEvent event = new FriendshipAcceptedEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            assertThat(event.getFriendshipId()).isEqualTo(FRIENDSHIP_ID);
            assertThat(event.getRequesterId()).isEqualTo(REQUESTER_ID);
            assertThat(event.getReceiverId()).isEqualTo(RECEIVER_ID);
        }

        @Test
        @DisplayName("BaseDomainEvent의 eventId와 occurredAt 자동 생성")
        void baseDomainEvent_AutoGeneratedFields() {
            FriendshipAcceptedEvent event = new FriendshipAcceptedEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            assertThat(event.getEventId()).isNotNull();
            assertThat(event.getOccurredAt()).isNotNull();
        }

        @Test
        @DisplayName("toString에 모든 필드 포함")
        void toString_ContainsAllFields() {
            FriendshipAcceptedEvent event = new FriendshipAcceptedEvent(
                    FRIENDSHIP_ID, REQUESTER_ID, RECEIVER_ID);

            String result = event.toString();
            assertThat(result).contains("FriendshipAcceptedEvent");
            assertThat(result).contains(FRIENDSHIP_ID.toString());
            assertThat(result).contains(REQUESTER_ID.toString());
            assertThat(result).contains(RECEIVER_ID.toString());
        }
    }
}
