create table products (
    price integer not null,
    stock integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    seller_id bigint not null,
    updated_at timestamp(6) not null,
    category varchar(50),
    image_key varchar(500),
    created_by varchar(255),
    description varchar(255) not null,
    name varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    deleted_at timestamp(6),
    primary key (id)
);

create table product_stock_histories (
    after_stock integer not null,
    before_stock integer not null,
    delta integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    seller_id bigint not null,
    change_type varchar(255) not null,
    primary key (id)
);

create table member_replicas (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);
