create table orders (
    total_amount numeric(19,2) not null,
    buyer_id bigint not null,
    cancel_requested_at timestamp(6),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6),
    id bigint generated by default as identity,
    paid_at timestamp(6),
    payment_id bigint unique,
    quantity bigint not null,
    updated_at timestamp(6),
    expired_at timestamp(6),
    order_number varchar(255) not null unique,
    origin_transaction_key varchar(255),
    payment_method varchar(255) not null,
    status varchar(255) not null,
    primary key (id)
);

create table order_items (
    amount numeric(19,2) not null,
    price numeric(19,2) not null,
    cancel_requested_at timestamp(6),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6),
    id bigint generated by default as identity,
    order_id bigint,
    receiver_id bigint not null,
    seller_id bigint not null,
    target_id bigint not null,
    updated_at timestamp(6),
    order_item_type varchar(255) not null,
    origin_transaction_key varchar(255),
    status varchar(255) not null,
    target_type varchar(255) not null,
    primary key (id),
    constraint fk_order_items_orders foreign key (order_id) references orders
);

create table core_member_replicas (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);

create index idx_order_items_order_id_status on order_items (order_id, status);
create index idx_order_status_created_at on orders (status, created_at);
