create table wishlists (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null unique,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    visibility varchar(255) not null,
    primary key (id)
);

create table wishlist_items (
    added_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6) not null,
    wishlist_id bigint not null,
    created_by varchar(255),
    updated_by varchar(255),
    wishlist_item_status varchar(255) not null,
    primary key (id)
);
