-- bc/core: Order (legacy) + Order V2

CREATE TABLE orders (
    total_amount numeric(38,2) NOT NULL,
    buyer_id bigint NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    order_number character varying(255) NOT NULL,
    payment_key character varying(255),
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PAYMENT_PENDING'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying, 'PARTIAL_CANCELED'::character varying, 'REFUNDED'::character varying])::text[])))
);

ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_item (
    price numeric(38,2) NOT NULL,
    quantity integer NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_snapshot_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    target_type character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT order_item_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

ALTER TABLE order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_v2 (
    total_amount numeric(19,2) NOT NULL,
    buyer_id bigint NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6),
    id bigint NOT NULL,
    paid_at timestamp(6),
    quantity bigint NOT NULL,
    updated_at timestamp(6),
    last_transaction_key character varying(255),
    order_number character varying(255) NOT NULL,
    payment_id bigint,
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT order_v2_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT order_v2_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'CANCEL_PENDING'::character varying, 'CANCELED'::character varying])::text[])))
);

ALTER TABLE order_v2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_v2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_item_v2 (
    amount numeric(19,2) NOT NULL,
    price numeric(19,2) NOT NULL,
    cancelled_at timestamp(6),
    created_at timestamp(6),
    id bigint NOT NULL,
    order_id bigint,
    receiver_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_id bigint NOT NULL,
    updated_at timestamp(6),
    order_item_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    target_type character varying(255) NOT NULL,
    CONSTRAINT order_item_v2_order_item_type_check CHECK (((order_item_type)::text = ANY ((ARRAY['NORMAL_ORDER'::character varying, 'FUNDING_GIFT'::character varying, 'NORMAL_GIFT'::character varying])::text[]))),
    CONSTRAINT order_item_v2_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT order_item_v2_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

ALTER TABLE order_item_v2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_item_v2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_item ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_item_v2 ADD CONSTRAINT order_item_v2_pkey PRIMARY KEY (id);
ALTER TABLE ONLY orders ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_payment_key_key UNIQUE (payment_key);
