-- bc/member: Members

CREATE TABLE members (
    birthday date,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    nickname character varying(100) NOT NULL,
    address character varying(255),
    auth_sub character varying(255),
    created_by character varying(255),
    email character varying(255) NOT NULL,
    name character varying(255),
    phone_num character varying(255),
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER'::character varying, 'SELLER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DORMANT'::character varying, 'WITHDRAWN'::character varying])::text[])))
);

ALTER TABLE members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE member_replica (
    id bigint NOT NULL,
    nickname character varying(255)
);

ALTER TABLE ONLY members ADD CONSTRAINT members_pkey PRIMARY KEY (id);
ALTER TABLE ONLY member_replica ADD CONSTRAINT member_replica_pkey PRIMARY KEY (id);
ALTER TABLE ONLY members ADD CONSTRAINT members_auth_sub_key UNIQUE (auth_sub);
ALTER TABLE ONLY members ADD CONSTRAINT members_email_key UNIQUE (email);
