-- bc/settlement: Settlement + Snapshots

CREATE TABLE settlement_item (
    expected_date date,
    paid_amount numeric(38,2),
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    retry_count integer NOT NULL DEFAULT 0,
    settlement_amount numeric(38,2),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6) NOT NULL,
    created_at timestamp(6),
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    ordered_at timestamp(6) NOT NULL,
    origin_id bigint,
    paid_at timestamp(6) NOT NULL,
    seller_id bigint NOT NULL,
    settled_at timestamp(6),
    target_id bigint NOT NULL,
    updated_at timestamp(6),
    order_number character varying(255) NOT NULL,
    status character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT settlement_item_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'READY'::character varying, 'FAIL'::character varying, 'MANUAL_CHECK'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT settlement_item_type_check CHECK (((type)::text = ANY ((ARRAY['ITEM_PAYMENT'::character varying, 'DEDUCTION_REFUND'::character varying])::text[])))
);

ALTER TABLE settlement_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlement_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE settlement_queue (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    settlement_item_id bigint NOT NULL,
    updated_at timestamp(6)
);

ALTER TABLE settlement_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlement_queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_snapshot (
    order_id bigint NOT NULL,
    ordered_at timestamp(6) NOT NULL,
    order_number character varying(255) NOT NULL
);

CREATE TABLE order_item_snapshot (
    amount numeric(38,2) NOT NULL,
    price numeric(38,2) NOT NULL,
    order_id bigint,
    order_item_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_id bigint NOT NULL,
    order_item_type character varying(255),
    target_type character varying(255),
    CONSTRAINT order_item_snapshot_order_item_type_check CHECK (((order_item_type)::text = ANY ((ARRAY['NORMAL_ORDER'::character varying, 'FUNDING_GIFT'::character varying, 'NORMAL_GIFT'::character varying])::text[]))),
    CONSTRAINT order_item_snapshot_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

CREATE TABLE payment_snapshot (
    method smallint,
    paid_amount numeric(38,2) NOT NULL,
    paid_at timestamp(6) NOT NULL,
    payment_id bigint NOT NULL,
    order_number character varying(255) NOT NULL,
    payment_key character varying(255) NOT NULL,
    transaction_key character varying(255) NOT NULL,
    CONSTRAINT payment_snapshot_method_check CHECK (((method >= 0) AND (method <= 0)))
);

ALTER TABLE ONLY settlement_item ADD CONSTRAINT settlement_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY settlement_queue ADD CONSTRAINT settlement_queue_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_snapshot ADD CONSTRAINT order_snapshot_pkey PRIMARY KEY (order_id);
ALTER TABLE ONLY order_item_snapshot ADD CONSTRAINT order_item_snapshot_pkey PRIMARY KEY (order_item_id);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_pkey PRIMARY KEY (payment_id);
ALTER TABLE ONLY order_snapshot ADD CONSTRAINT order_snapshot_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_item_snapshot ADD CONSTRAINT order_item_snapshot_target_id_key UNIQUE (target_id);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_payment_key_key UNIQUE (payment_key);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_transaction_key_key UNIQUE (transaction_key);
ALTER TABLE ONLY settlement_item ADD CONSTRAINT uk_target_id_type UNIQUE (target_id, type);
