-- bc/core: Funding

CREATE TABLE funding_member (
    id bigint NOT NULL,
    auth_sub character varying(255),
    nickname character varying(255)
);

CREATE TABLE funding (
    current_amount integer NOT NULL,
    target_amount integer NOT NULL,
    version bigint,
    achieved_at timestamp(6),
    closed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    deadline timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wishlist_item_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    CONSTRAINT funding_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'ACHIEVED'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying, 'EXPIRED'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE funding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME funding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE funding_participant_member (
    amount integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    funding_id bigint NOT NULL,
    id bigint NOT NULL,
    participant_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE funding_participant_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME funding_participant_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY funding_member ADD CONSTRAINT funding_member_pkey PRIMARY KEY (id);
ALTER TABLE ONLY funding ADD CONSTRAINT funding_pkey PRIMARY KEY (id);
ALTER TABLE ONLY funding_participant_member ADD CONSTRAINT funding_participant_member_pkey PRIMARY KEY (id);
