-- bc/settlement: Snapshots, Settlement

create table order_snapshot (
    order_id bigint not null,
    ordered_at timestamp(6) not null,
    order_number varchar(255) not null unique,
    primary key (order_id)
);

create table order_item_snapshot (
    amount numeric(38,2) not null,
    price numeric(38,2) not null,
    order_id bigint,
    order_item_id bigint not null,
    seller_id bigint not null,
    target_id bigint not null unique,
    order_item_type varchar(255),
    target_type varchar(255),
    primary key (order_item_id)
);

create table payment_snapshot (
    paid_amount numeric(38,2) not null,
    paid_at timestamp(6) not null,
    payment_id bigint not null,
    method varchar(255),
    order_number varchar(255) not null unique,
    payment_key varchar(255) not null unique,
    transaction_key varchar(255) not null unique,
    primary key (payment_id)
);

create table settlement_item (
    expected_date date,
    paid_amount numeric(38,2),
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    retry_count integer not null,
    settlement_amount numeric(38,2),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6) not null,
    created_at timestamp(6),
    history_id bigint,
    id bigint generated by default as identity,
    order_id bigint not null,
    order_item_id bigint not null,
    ordered_at timestamp(6) not null,
    origin_id bigint,
    paid_at timestamp(6) not null,
    seller_id bigint not null,
    settled_at timestamp(6),
    target_id bigint not null,
    updated_at timestamp(6),
    order_number varchar(255) not null,
    status varchar(255),
    type varchar(255) not null,
    primary key (id),
    constraint uk_target_id_type unique (target_id, type)
);

create table settlement_queue (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    settlement_item_id bigint not null,
    updated_at timestamp(6),
    status varchar(255) not null,
    primary key (id),
    unique (settlement_item_id)
);

create table settlement_history (
    item_count integer not null,
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    sales_amount numeric(38,2),
    settlement_amount numeric(38,2),
    settlement_date date not null,
    id bigint generated by default as identity,
    reference_history_id bigint,
    seller_id bigint not null,
    settled_at timestamp(6),
    status varchar(255),
    primary key (id),
    unique (seller_id, settlement_date)
);
