-- bc/core: Wallet

CREATE TABLE wallet (
    balance numeric(38,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    version bigint,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wallet_history (
    amount numeric(38,2) NOT NULL,
    balance_after numeric(38,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wallet_id bigint NOT NULL,
    created_by character varying(255),
    reference_id character varying(255) NOT NULL,
    reference_type character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    updated_by character varying(255)
);

ALTER TABLE wallet_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wallet_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY wallet ADD CONSTRAINT wallet_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wallet_history ADD CONSTRAINT wallet_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wallet ADD CONSTRAINT wallet_member_id_key UNIQUE (member_id);
