-- bc/catalog: Product, Wishlist, Cart

create table product (
    price integer not null,
    stock integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    seller_id bigint not null,
    updated_at timestamp(6) not null,
    category varchar(50),
    image_key varchar(500),
    created_by varchar(255),
    description varchar(255) not null,
    name varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table product_stock_history (
    after_stock integer not null,
    before_stock integer not null,
    delta integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    seller_id bigint not null,
    change_type varchar(255) not null,
    primary key (id)
);

create table wishlist (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    visibility varchar(255) not null,
    primary key (id)
);

create table wishlist_item (
    added_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6) not null,
    wishlist_id bigint not null,
    created_by varchar(255),
    updated_by varchar(255),
    wishlist_item_status varchar(255) not null,
    primary key (id)
);

create table cart (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint unique,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table cart_item (
    amount numeric(38,2),
    cart_id bigint,
    id bigint generated by default as identity,
    target_id bigint,
    target_type varchar(255),
    wishlist_item_status varchar(255),
    primary key (id)
);
