-- bc/core: Funding

create table funding (
    current_amount integer not null,
    target_amount integer not null,
    achieved_at timestamp(6),
    closed_at timestamp(6),
    created_at timestamp(6) not null,
    deadline timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    receiver_id bigint not null,
    updated_at timestamp(6) not null,
    version bigint not null,
    wishlist_item_id bigint not null,
    status varchar(20) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table funding_participant_member (
    amount integer not null,
    created_at timestamp(6) not null,
    funding_id bigint not null,
    id bigint generated by default as identity,
    participant_id bigint not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    nick_name varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);
