-- bc/core: PaymentCancel

create table payment_cancels (
    cancel_amount numeric(19,2) not null,
    canceled_at timestamp(6) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    payment_id bigint not null,
    updated_at timestamp(6) not null,
    cancel_reason varchar(500) not null,
    created_by varchar(255),
    transaction_key varchar(255) not null unique,
    updated_by varchar(255),
    primary key (id),
    constraint fk_payment_cancels_payment foreign key (payment_id) references payment(id)
);

create index idx_payment_cancels_payment_id on payment_cancels(payment_id);
