-- bc/core: Payment, Wallet

create table payment (
    origin_amount numeric(19,2) not null,
    paid_amount numeric(19,2) not null,
    refunded_amount numeric(19,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    order_id bigint,
    paid_at timestamp(6),
    updated_at timestamp(6) not null,
    method varchar(50) not null,
    status varchar(50) not null,
    type varchar(50) not null,
    approve_code varchar(255),
    created_by varchar(255),
    last_transaction_key varchar(255),
    order_items_json TEXT not null,
    order_number varchar(255) not null,
    payment_key varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table payment_history (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    payment_id bigint not null,
    updated_at timestamp(6) not null,
    event_type varchar(50) not null,
    created_by varchar(255),
    history_key varchar(255) not null unique,
    metadata TEXT,
    updated_by varchar(255),
    primary key (id)
);

create table wallet (
    balance numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null unique,
    updated_at timestamp(6) not null,
    version bigint,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table wallet_history (
    amount numeric(38,2) not null,
    balance_after numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    wallet_id bigint not null,
    created_by varchar(255),
    reference_id varchar(255) not null,
    reference_type varchar(255) not null,
    transaction_type varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);
