-- bc/member: Members, Friendships, Replicas

create table members (
    birthday date,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    nickname varchar(100) not null,
    address varchar(255),
    auth_sub varchar(255) unique,
    created_by varchar(255),
    email varchar(255) not null unique,
    name varchar(255),
    phone_num varchar(255),
    role varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table friendships (
    accepted_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    receiver_id bigint not null,
    requester_id bigint not null,
    updated_at timestamp(6) not null,
    status varchar(20) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table member_replica (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);

create table core_member_replica (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);
