-- bc/catalog: Products, Wishlists, Carts

CREATE TABLE product (
    price integer NOT NULL,
    stock integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    seller_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    image_key character varying(500),
    category character varying(50),
    CONSTRAINT product_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'REJECTED'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT product_category_check CHECK (((category)::text = ANY ((ARRAY['ELECTRONICS'::character varying, 'BEAUTY'::character varying, 'FASHION'::character varying, 'LIVING'::character varying, 'FOODS'::character varying, 'TOYS'::character varying, 'OUTDOOR'::character varying, 'PET'::character varying, 'KITCHEN'::character varying])::text[])))
);

ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE product_stock_history (
    after_stock integer NOT NULL,
    before_stock integer NOT NULL,
    delta integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    change_type character varying(255) NOT NULL,
    CONSTRAINT product_stock_history_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['MANUAL_ADJUST'::character varying, 'ORDER_DEDUCT'::character varying, 'ORDER_RESTORE'::character varying])::text[])))
);

ALTER TABLE product_stock_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME product_stock_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wishlist (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    visibility character varying(255) NOT NULL,
    CONSTRAINT wishlist_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'FRIENDS_ONLY'::character varying])::text[])))
);

ALTER TABLE wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wishlist_item (
    added_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wishlist_id bigint NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    wishlist_item_status character varying(255) NOT NULL,
    CONSTRAINT wishlist_item_wishlist_item_status_check CHECK (((wishlist_item_status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'REQUESTED_CONFIRM'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE wishlist_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wishlist_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cart (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cart_item (
    amount numeric(38,2),
    cart_id bigint,
    id bigint NOT NULL,
    target_id bigint,
    target_type character varying(255),
    wishlist_item_status character varying(255),
    CONSTRAINT cart_item_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[]))),
    CONSTRAINT cart_item_wishlist_item_status_check CHECK (((wishlist_item_status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'REQUESTED_CONFIRM'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY product ADD CONSTRAINT product_pkey PRIMARY KEY (id);
ALTER TABLE ONLY product_stock_history ADD CONSTRAINT product_stock_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wishlist ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wishlist_item ADD CONSTRAINT wishlist_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cart ADD CONSTRAINT cart_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cart_item ADD CONSTRAINT cart_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cart ADD CONSTRAINT cart_member_id_key UNIQUE (member_id);
