-- bc/core: Payment

CREATE TABLE payment (
    origin_amount numeric(19,2) NOT NULL,
    paid_amount numeric(19,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    paid_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    method character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    type character varying(50) NOT NULL,
    approve_code character varying(255),
    created_by character varying(255),
    idempotency_key character varying(255) NOT NULL,
    last_transaction_key character varying(255),
    order_id character varying(255) NOT NULL,
    order_items_json text NOT NULL,
    payment_key character varying(255),
    updated_by character varying(255),
    CONSTRAINT payment_method_check CHECK (((method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying, 'RECEIVED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT payment_type_check CHECK (((type)::text = ANY ((ARRAY['FUNDING'::character varying, 'DEPOSIT_CHARGE'::character varying])::text[])))
);

ALTER TABLE payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE payment_history (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    payment_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    event_type character varying(50) NOT NULL,
    created_by character varying(255),
    idempotency_key character varying(255) NOT NULL,
    metadata text,
    updated_by character varying(255),
    CONSTRAINT payment_history_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying, 'RECEIVED'::character varying, 'REFUNDED'::character varying, 'CANCEL_FAILED'::character varying])::text[])))
);

ALTER TABLE payment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY payment ADD CONSTRAINT payment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY payment_history ADD CONSTRAINT payment_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY payment ADD CONSTRAINT payment_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE ONLY payment_history ADD CONSTRAINT payment_history_idempotency_key_key UNIQUE (idempotency_key);
