CREATE TABLE friendships (
    id            bigint NOT NULL,
    requester_id  bigint NOT NULL,
    receiver_id   bigint NOT NULL,
    status        character varying(20) NOT NULL DEFAULT 'PENDING',
    created_at    timestamp(6) NOT NULL,
    accepted_at   timestamp(6),
    updated_at    timestamp(6) NOT NULL,
    created_by    character varying(255),
    updated_by    character varying(255)
);

ALTER TABLE friendships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME friendships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY friendships ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);
ALTER TABLE ONLY friendships ADD CONSTRAINT uk_friendship_pair UNIQUE (requester_id, receiver_id);
ALTER TABLE ONLY friendships ADD CONSTRAINT fk_friendship_requester FOREIGN KEY (requester_id) REFERENCES members(id);
ALTER TABLE ONLY friendships ADD CONSTRAINT fk_friendship_receiver FOREIGN KEY (receiver_id) REFERENCES members(id);

CREATE INDEX idx_friendship_receiver_status ON friendships (receiver_id, status);
CREATE INDEX idx_friendship_requester_status ON friendships (requester_id, status);
