-- bc/notification: Notification

CREATE TABLE notifications
(
    id                  bigint                 NOT NULL,
    recipient_id        bigint                 NOT NULL,
    type                character varying(50)  NOT NULL,
    title               character varying(200) NOT NULL,
    content             character varying(500) NOT NULL,
    is_read             boolean                NOT NULL DEFAULT false,
    read_at             timestamp(6),
    reference_id        character varying(50),
    reference_type      character varying(50),
    source_event_id     character varying(100) NOT NULL,
    source_event_type   character varying(100) NOT NULL,
    source_event_source character varying(100) NOT NULL,
    created_at          timestamp(6)           NOT NULL,
    updated_at          timestamp(6)           NOT NULL,
    created_by          character varying(255),
    updated_by          character varying(255)
);

ALTER TABLE notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME notifications_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
  );

ALTER TABLE ONLY notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

CREATE INDEX idx_notifications_recipient_id ON notifications (recipient_id);
CREATE INDEX idx_notifications_recipient_unread ON notifications (recipient_id) WHERE is_read = false;
CREATE UNIQUE INDEX idx_notifications_source_event_id ON notifications (source_event_id);
