-- settlement_history 테이블 생성 (정산 이력)

CREATE TABLE settlement_history (
    id bigint NOT NULL,
    seller_id bigint NOT NULL,
    sales_amount numeric(38,2),
    platform_fee numeric(38,2),
    pg_fee numeric(38,2),
    settlement_amount numeric(38,2),
    item_count integer NOT NULL,
    status character varying(255),
    reference_history_id bigint,
    settlement_date date NOT NULL,
    settled_at timestamp(6),
    CONSTRAINT settlement_history_pkey PRIMARY KEY (id),
    CONSTRAINT uk_seller_settlement_date UNIQUE (seller_id, settlement_date),
    CONSTRAINT settlement_history_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE settlement_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlement_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
