-- =============================================================================
-- V1: Baseline Schema
-- Giftify API Server - PostgreSQL 16
-- Generated from Hibernate DDL export, cleaned for Flyway
-- =============================================================================

-- ---------------------------------------------------------------------------
-- bc/member: Members
-- ---------------------------------------------------------------------------

CREATE TABLE members (
    birthday date,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    nickname character varying(100) NOT NULL,
    address character varying(255),
    auth_sub character varying(255),
    created_by character varying(255),
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    phone_num character varying(255),
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER'::character varying, 'SELLER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DORMANT'::character varying, 'WITHDRAWN'::character varying])::text[])))
);

ALTER TABLE members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE member_replica (
    id bigint NOT NULL,
    nickname character varying(255)
);

-- ---------------------------------------------------------------------------
-- bc/catalog: Products
-- ---------------------------------------------------------------------------

CREATE TABLE product (
    price integer NOT NULL,
    stock integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    seller_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT product_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'REJECTED'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE product_stock_history (
    after_stock integer NOT NULL,
    before_stock integer NOT NULL,
    delta integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    change_type character varying(255) NOT NULL,
    CONSTRAINT product_stock_history_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['MANUAL_ADJUST'::character varying, 'ORDER_DEDUCT'::character varying, 'ORDER_RESTORE'::character varying])::text[])))
);

ALTER TABLE product_stock_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME product_stock_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/catalog: Wishlists
-- ---------------------------------------------------------------------------

CREATE TABLE wishlist (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    visibility character varying(255) NOT NULL,
    CONSTRAINT wishlist_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'FRIENDS_ONLY'::character varying])::text[])))
);

ALTER TABLE wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wishlist_item (
    added_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wishlist_id bigint NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    wishlist_item_status character varying(255) NOT NULL,
    CONSTRAINT wishlist_item_wishlist_item_status_check CHECK (((wishlist_item_status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'REQUESTED_CONFIRM'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE wishlist_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wishlist_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/catalog: Carts
-- ---------------------------------------------------------------------------

CREATE TABLE cart (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cart_item (
    amount numeric(38,2),
    cart_id bigint,
    id bigint NOT NULL,
    target_id bigint,
    target_type character varying(255),
    wishlist_item_status character varying(255),
    CONSTRAINT cart_item_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[]))),
    CONSTRAINT cart_item_wishlist_item_status_check CHECK (((wishlist_item_status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'REQUESTED_CONFIRM'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/core: Funding
-- ---------------------------------------------------------------------------

CREATE TABLE funding_member (
    id bigint NOT NULL,
    auth_sub character varying(255),
    nickname character varying(255)
);

CREATE TABLE funding (
    current_amount integer NOT NULL,
    target_amount integer NOT NULL,
    achieved_at timestamp(6),
    closed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    deadline timestamp(6) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wishlist_item_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    CONSTRAINT funding_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'ACHIEVED'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying, 'EXPIRED'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE funding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME funding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE funding_participant_member (
    amount integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    funding_id bigint NOT NULL,
    id bigint NOT NULL,
    participant_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE funding_participant_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME funding_participant_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/core: Wallet
-- ---------------------------------------------------------------------------

CREATE TABLE wallet (
    balance numeric(38,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    version bigint,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wallet_history (
    amount numeric(38,2) NOT NULL,
    balance_after numeric(38,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    wallet_id bigint NOT NULL,
    created_by character varying(255),
    reference_id character varying(255) NOT NULL,
    reference_type character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    updated_by character varying(255)
);

ALTER TABLE wallet_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wallet_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/core: Payment
-- ---------------------------------------------------------------------------

CREATE TABLE payment (
    origin_amount numeric(19,2) NOT NULL,
    paid_amount numeric(19,2) NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    paid_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    method character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    type character varying(50) NOT NULL,
    approve_code character varying(255),
    created_by character varying(255),
    idempotency_key character varying(255) NOT NULL,
    last_transaction_key character varying(255),
    order_id character varying(255) NOT NULL,
    order_items_json text NOT NULL,
    payment_key character varying(255),
    updated_by character varying(255),
    CONSTRAINT payment_method_check CHECK (((method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying, 'RECEIVED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT payment_type_check CHECK (((type)::text = ANY ((ARRAY['FUNDING'::character varying, 'DEPOSIT_CHARGE'::character varying])::text[])))
);

ALTER TABLE payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE payment_history (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    payment_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    event_type character varying(50) NOT NULL,
    created_by character varying(255),
    idempotency_key character varying(255) NOT NULL,
    metadata text,
    updated_by character varying(255),
    CONSTRAINT payment_history_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying, 'RECEIVED'::character varying, 'REFUNDED'::character varying, 'CANCEL_FAILED'::character varying])::text[])))
);

ALTER TABLE payment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/core: Order (legacy)
-- ---------------------------------------------------------------------------

CREATE TABLE orders (
    total_amount numeric(38,2) NOT NULL,
    buyer_id bigint NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    order_number character varying(255) NOT NULL,
    payment_key character varying(255),
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PAYMENT_PENDING'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying, 'PARTIAL_CANCELED'::character varying, 'REFUNDED'::character varying])::text[])))
);

ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_item (
    price numeric(38,2) NOT NULL,
    quantity integer NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_snapshot_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by character varying(255),
    target_type character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT order_item_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

ALTER TABLE order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/core: Order V2
-- ---------------------------------------------------------------------------

CREATE TABLE order_v2 (
    total_amount numeric(19,2) NOT NULL,
    buyer_id bigint NOT NULL,
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6),
    id bigint NOT NULL,
    paid_at timestamp(6),
    quantity bigint NOT NULL,
    updated_at timestamp(6),
    last_transaction_key character varying(255),
    order_number character varying(255) NOT NULL,
    payment_key character varying(255),
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT order_v2_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'KAKAO_PAY'::character varying, 'NAVER_PAY'::character varying, 'TOSS_PAY'::character varying, 'ACCOUNT_TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'BANK_TRANSFER'::character varying, 'DEPOSIT'::character varying, 'POINT'::character varying])::text[]))),
    CONSTRAINT order_v2_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'CANCELED'::character varying])::text[])))
);

ALTER TABLE order_v2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_v2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_item_v2 (
    amount numeric(19,2) NOT NULL,
    price numeric(19,2) NOT NULL,
    cancelled_at timestamp(6),
    created_at timestamp(6),
    id bigint NOT NULL,
    order_id bigint,
    receiver_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_id bigint NOT NULL,
    updated_at timestamp(6),
    order_item_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    target_type character varying(255) NOT NULL,
    CONSTRAINT order_item_v2_order_item_type_check CHECK (((order_item_type)::text = ANY ((ARRAY['NORMAL_ORDER'::character varying, 'FUNDING_GIFT'::character varying, 'NORMAL_GIFT'::character varying])::text[]))),
    CONSTRAINT order_item_v2_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT order_item_v2_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

ALTER TABLE order_item_v2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_item_v2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/settlement: Settlement
-- ---------------------------------------------------------------------------

CREATE TABLE settlement_item (
    expected_date date,
    paid_amount numeric(38,2),
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    retry_count integer NOT NULL,
    settlement_amount numeric(38,2),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6) NOT NULL,
    created_at timestamp(6),
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    ordered_at timestamp(6) NOT NULL,
    origin_id bigint,
    paid_at timestamp(6) NOT NULL,
    seller_id bigint NOT NULL,
    settled_at timestamp(6),
    target_id bigint NOT NULL,
    updated_at timestamp(6),
    order_number character varying(255) NOT NULL,
    status character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT settlement_item_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'READY'::character varying, 'FAIL'::character varying, 'MANUAL_CHECK'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT settlement_item_type_check CHECK (((type)::text = ANY ((ARRAY['ITEM_PAYMENT'::character varying, 'DEDUCTION_REFUND'::character varying])::text[])))
);

ALTER TABLE settlement_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlement_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE settlement_queue (
    created_at timestamp(6) NOT NULL,
    id bigint NOT NULL,
    settlement_item_id bigint NOT NULL,
    updated_at timestamp(6)
);

ALTER TABLE settlement_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlement_queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---------------------------------------------------------------------------
-- bc/settlement: Snapshots
-- ---------------------------------------------------------------------------

CREATE TABLE order_snapshot (
    order_id bigint NOT NULL,
    ordered_at timestamp(6) NOT NULL,
    order_number character varying(255) NOT NULL
);

CREATE TABLE order_item_snapshot (
    amount numeric(38,2) NOT NULL,
    price numeric(38,2) NOT NULL,
    order_id bigint,
    order_item_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    target_id bigint NOT NULL,
    order_item_type character varying(255),
    target_type character varying(255),
    CONSTRAINT order_item_snapshot_order_item_type_check CHECK (((order_item_type)::text = ANY ((ARRAY['NORMAL_ORDER'::character varying, 'FUNDING_GIFT'::character varying, 'NORMAL_GIFT'::character varying])::text[]))),
    CONSTRAINT order_item_snapshot_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['GENERAL_PRODUCT'::character varying, 'FUNDING_PENDING'::character varying, 'FUNDING'::character varying])::text[])))
);

CREATE TABLE payment_snapshot (
    method smallint,
    paid_amount numeric(38,2) NOT NULL,
    paid_at timestamp(6) NOT NULL,
    payment_id bigint NOT NULL,
    order_number character varying(255) NOT NULL,
    payment_key character varying(255) NOT NULL,
    transaction_key character varying(255) NOT NULL,
    CONSTRAINT payment_snapshot_method_check CHECK (((method >= 0) AND (method <= 0)))
);

-- ===========================================================================
-- PRIMARY KEY CONSTRAINTS
-- ===========================================================================

ALTER TABLE ONLY members ADD CONSTRAINT members_pkey PRIMARY KEY (id);
ALTER TABLE ONLY member_replica ADD CONSTRAINT member_replica_pkey PRIMARY KEY (id);
ALTER TABLE ONLY product ADD CONSTRAINT product_pkey PRIMARY KEY (id);
ALTER TABLE ONLY product_stock_history ADD CONSTRAINT product_stock_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wishlist ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wishlist_item ADD CONSTRAINT wishlist_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cart ADD CONSTRAINT cart_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cart_item ADD CONSTRAINT cart_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY funding_member ADD CONSTRAINT funding_member_pkey PRIMARY KEY (id);
ALTER TABLE ONLY funding ADD CONSTRAINT funding_pkey PRIMARY KEY (id);
ALTER TABLE ONLY funding_participant_member ADD CONSTRAINT funding_participant_member_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wallet ADD CONSTRAINT wallet_pkey PRIMARY KEY (id);
ALTER TABLE ONLY wallet_history ADD CONSTRAINT wallet_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY payment ADD CONSTRAINT payment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY payment_history ADD CONSTRAINT payment_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_item ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_item_v2 ADD CONSTRAINT order_item_v2_pkey PRIMARY KEY (id);
ALTER TABLE ONLY settlement_item ADD CONSTRAINT settlement_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY settlement_queue ADD CONSTRAINT settlement_queue_pkey PRIMARY KEY (id);
ALTER TABLE ONLY order_snapshot ADD CONSTRAINT order_snapshot_pkey PRIMARY KEY (order_id);
ALTER TABLE ONLY order_item_snapshot ADD CONSTRAINT order_item_snapshot_pkey PRIMARY KEY (order_item_id);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_pkey PRIMARY KEY (payment_id);

-- ===========================================================================
-- UNIQUE CONSTRAINTS
-- ===========================================================================

ALTER TABLE ONLY members ADD CONSTRAINT members_auth_sub_key UNIQUE (auth_sub);
ALTER TABLE ONLY members ADD CONSTRAINT members_email_key UNIQUE (email);
ALTER TABLE ONLY cart ADD CONSTRAINT cart_member_id_key UNIQUE (member_id);
ALTER TABLE ONLY wallet ADD CONSTRAINT wallet_member_id_key UNIQUE (member_id);
ALTER TABLE ONLY payment ADD CONSTRAINT payment_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE ONLY payment_history ADD CONSTRAINT payment_history_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE ONLY orders ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_v2 ADD CONSTRAINT order_v2_payment_key_key UNIQUE (payment_key);
ALTER TABLE ONLY order_snapshot ADD CONSTRAINT order_snapshot_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY order_item_snapshot ADD CONSTRAINT order_item_snapshot_target_id_key UNIQUE (target_id);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_payment_key_key UNIQUE (payment_key);
ALTER TABLE ONLY payment_snapshot ADD CONSTRAINT payment_snapshot_transaction_key_key UNIQUE (transaction_key);
ALTER TABLE ONLY settlement_item ADD CONSTRAINT uk_target_id_type UNIQUE (target_id, type);

-- ===========================================================================
-- INDEXES
-- ===========================================================================

CREATE INDEX idx_funding_wishlist_status ON funding USING btree (wishlist_item_id, status);
CREATE INDEX idx_settlement_order_id ON settlement_item USING btree (order_id);
CREATE INDEX idx_settlement_status_created_retry ON settlement_item USING btree (status, created_at, retry_count);

-- ===========================================================================
-- FOREIGN KEY CONSTRAINTS
-- ===========================================================================

ALTER TABLE ONLY cart_item ADD CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart(id);
ALTER TABLE ONLY funding_participant_member ADD CONSTRAINT fk_funding_participant_funding FOREIGN KEY (funding_id) REFERENCES funding(id);
ALTER TABLE ONLY settlement_queue ADD CONSTRAINT fk_settlement_queue_item FOREIGN KEY (settlement_item_id) REFERENCES settlement_item(id);
ALTER TABLE ONLY order_item_v2 ADD CONSTRAINT fk_order_item_v2_order FOREIGN KEY (order_id) REFERENCES order_v2(id);
