-- V1__init.sql
-- Giftify 통합 초기 스키마
-- Generated from Hibernate 6.6 SchemaExport (PostgreSQL dialect)
-- Enum CHECK constraints intentionally removed (unstable phase)

-- =============================================================================
-- Section 1: Application Tables (Entity-based)
-- =============================================================================

-- bc/member
create table members (
    birthday date,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    nickname varchar(100) not null,
    address varchar(255),
    auth_sub varchar(255) unique,
    created_by varchar(255),
    email varchar(255) not null unique,
    name varchar(255),
    phone_num varchar(255),
    role varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table friendships (
    accepted_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    receiver_id bigint not null,
    requester_id bigint not null,
    updated_at timestamp(6) not null,
    status varchar(20) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

-- bc/member, bc/core: Replica tables
create table member_replica (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);

create table core_member_replica (
    id bigint not null,
    nickname varchar(255),
    primary key (id)
);

-- bc/catalog
create table product (
    price integer not null,
    stock integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    seller_id bigint not null,
    updated_at timestamp(6) not null,
    category varchar(50),
    image_key varchar(500),
    created_by varchar(255),
    description varchar(255) not null,
    name varchar(255) not null,
    status varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table product_stock_history (
    after_stock integer not null,
    before_stock integer not null,
    delta integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    seller_id bigint not null,
    change_type varchar(255) not null,
    primary key (id)
);

create table wishlist (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    visibility varchar(255) not null,
    primary key (id)
);

create table wishlist_item (
    added_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6) not null,
    wishlist_id bigint not null,
    created_by varchar(255),
    updated_by varchar(255),
    wishlist_item_status varchar(255) not null,
    primary key (id)
);

create table cart (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint unique,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table cart_item (
    amount numeric(38,2),
    cart_id bigint,
    id bigint generated by default as identity,
    target_id bigint,
    target_type varchar(255),
    wishlist_item_status varchar(255),
    primary key (id)
);

-- bc/core: Funding
create table funding (
    current_amount integer not null,
    target_amount integer not null,
    achieved_at timestamp(6),
    closed_at timestamp(6),
    created_at timestamp(6) not null,
    deadline timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    receiver_id bigint not null,
    updated_at timestamp(6) not null,
    version bigint not null,
    wishlist_item_id bigint not null,
    status varchar(20) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table funding_participant_member (
    amount integer not null,
    created_at timestamp(6) not null,
    funding_id bigint not null,
    id bigint generated by default as identity,
    participant_id bigint not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    nick_name varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

-- bc/core: Order
create table orders (
    total_amount numeric(19,2) not null,
    buyer_id bigint not null,
    cancel_requested_at timestamp(6),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6),
    created_at timestamp(6),
    id bigint generated by default as identity,
    paid_at timestamp(6),
    payment_id bigint unique,
    quantity bigint not null,
    updated_at timestamp(6),
    order_number varchar(255) not null unique,
    origin_transaction_key varchar(255),
    payment_method varchar(255) not null,
    status varchar(255) not null,
    primary key (id)
);

create table order_items (
    amount numeric(19,2) not null,
    price numeric(19,2) not null,
    cancel_requested_at timestamp(6),
    cancelled_at timestamp(6),
    created_at timestamp(6),
    id bigint generated by default as identity,
    order_id bigint,
    receiver_id bigint not null,
    seller_id bigint not null,
    target_id bigint not null,
    updated_at timestamp(6),
    order_item_type varchar(255) not null,
    origin_transaction_key varchar(255),
    status varchar(255) not null,
    target_type varchar(255) not null,
    primary key (id)
);

-- bc/core: Payment
create table payment (
    origin_amount numeric(19,2) not null,
    paid_amount numeric(19,2) not null,
    refunded_amount numeric(19,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    order_id bigint,
    paid_at timestamp(6),
    updated_at timestamp(6) not null,
    method varchar(50) not null,
    status varchar(50) not null,
    type varchar(50) not null,
    approve_code varchar(255),
    created_by varchar(255),
    last_transaction_key varchar(255),
    order_items_json TEXT not null,
    order_number varchar(255) not null,
    payment_key varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table payment_history (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    payment_id bigint not null,
    updated_at timestamp(6) not null,
    event_type varchar(50) not null,
    created_by varchar(255),
    history_key varchar(255) not null unique,
    metadata TEXT,
    updated_by varchar(255),
    primary key (id)
);

-- bc/core: Wallet
create table wallet (
    balance numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null unique,
    updated_at timestamp(6) not null,
    version bigint,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table wallet_history (
    amount numeric(38,2) not null,
    balance_after numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    wallet_id bigint not null,
    created_by varchar(255),
    reference_id varchar(255) not null,
    reference_type varchar(255) not null,
    transaction_type varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

-- bc/settlement: Snapshots
create table order_snapshot (
    order_id bigint not null,
    ordered_at timestamp(6) not null,
    order_number varchar(255) not null unique,
    primary key (order_id)
);

create table order_item_snapshot (
    amount numeric(38,2) not null,
    price numeric(38,2) not null,
    order_id bigint,
    order_item_id bigint not null,
    seller_id bigint not null,
    target_id bigint not null unique,
    order_item_type varchar(255),
    target_type varchar(255),
    primary key (order_item_id)
);

create table payment_snapshot (
    paid_amount numeric(38,2) not null,
    paid_at timestamp(6) not null,
    payment_id bigint not null,
    method varchar(255),
    order_number varchar(255) not null unique,
    payment_key varchar(255) not null unique,
    transaction_key varchar(255) not null unique,
    primary key (payment_id)
);

-- bc/settlement: Settlement
create table settlement_item (
    expected_date date,
    paid_amount numeric(38,2),
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    retry_count integer not null,
    settlement_amount numeric(38,2),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6) not null,
    created_at timestamp(6),
    history_id bigint,
    id bigint generated by default as identity,
    order_id bigint not null,
    order_item_id bigint not null,
    ordered_at timestamp(6) not null,
    origin_id bigint,
    paid_at timestamp(6) not null,
    seller_id bigint not null,
    settled_at timestamp(6),
    target_id bigint not null,
    updated_at timestamp(6),
    order_number varchar(255) not null,
    status varchar(255),
    type varchar(255) not null,
    primary key (id),
    constraint uk_target_id_type unique (target_id, type)
);

create table settlement_queue (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    settlement_item_id bigint not null,
    updated_at timestamp(6),
    status varchar(255) not null,
    primary key (id),
    unique (settlement_item_id)
);

create table settlement_history (
    item_count integer not null,
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    sales_amount numeric(38,2),
    settlement_amount numeric(38,2),
    settlement_date date not null,
    id bigint generated by default as identity,
    reference_history_id bigint,
    seller_id bigint not null,
    settled_at timestamp(6),
    status varchar(255),
    primary key (id),
    unique (seller_id, settlement_date)
);

-- bc/notification
create table notifications (
    is_read boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    read_at timestamp(6),
    recipient_id bigint not null,
    updated_at timestamp(6) not null,
    reference_id varchar(50),
    reference_type varchar(50),
    type varchar(50) not null,
    source_event_id varchar(100) not null,
    source_event_source varchar(100) not null,
    source_event_type varchar(100) not null,
    title varchar(200) not null,
    content varchar(500) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

-- =============================================================================
-- Section 2: Indexes
-- =============================================================================

create index idx_funding_wishlist_status on funding (wishlist_item_id, status);
create index idx_order_items_order_id_status on order_items (order_id, status);
create index idx_settlement_status_created_retry on settlement_item (status, created_at, retry_count);
create index idx_settlement_order_id on settlement_item (order_id);

-- =============================================================================
-- Section 3: Foreign Keys
-- =============================================================================

alter table if exists cart_item
    add constraint fk_cart_item_cart foreign key (cart_id) references cart;

alter table if exists funding_participant_member
    add constraint fk_funding_participant_funding foreign key (funding_id) references funding;

alter table if exists order_items
    add constraint fk_order_items_orders foreign key (order_id) references orders;

alter table if exists settlement_queue
    add constraint fk_settlement_queue_item foreign key (settlement_item_id) references settlement_item;

-- =============================================================================
-- Section 4: Framework Tables
-- =============================================================================

-- Spring Modulith Event Publication (v1.3.1)
CREATE TABLE IF NOT EXISTS event_publication
(
    id               UUID NOT NULL,
    listener_id      TEXT NOT NULL,
    event_type       TEXT NOT NULL,
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date  TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS event_publication_serialized_event_hash_idx
    ON event_publication USING hash (serialized_event);

CREATE INDEX IF NOT EXISTS event_publication_by_completion_date_idx
    ON event_publication (completion_date);

CREATE TABLE IF NOT EXISTS event_publication_archive
(
    id               UUID NOT NULL,
    listener_id      TEXT NOT NULL,
    event_type       TEXT NOT NULL,
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date  TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS event_publication_archive_serialized_event_hash_idx
    ON event_publication_archive USING hash (serialized_event);

CREATE INDEX IF NOT EXISTS event_publication_archive_by_completion_date_idx
    ON event_publication_archive (completion_date);

-- Spring Batch 5.2 Meta Tables
CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
