-- Spring Batch 5.2 -> 6.0: BATCH_JOB_SEQ -> BATCH_JOB_INSTANCE_SEQ
ALTER SEQUENCE IF EXISTS BATCH_JOB_SEQ RENAME TO BATCH_JOB_INSTANCE_SEQ;

-- If BATCH_JOB_SEQ didn't exist (fresh DB), create the new sequence
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
