create table notifications (
    is_read boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    read_at timestamp(6),
    recipient_id bigint not null,
    updated_at timestamp(6) not null,
    reference_id varchar(50),
    reference_type varchar(50),
    type varchar(50) not null,
    source_event_id varchar(100) not null,
    source_event_source varchar(100) not null,
    source_event_type varchar(100) not null,
    title varchar(200) not null,
    content varchar(500) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);
