// Bootstrap API Server - 애플리케이션 진입점

plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

dependencies {
    implementation(project(":bc:shared"))
    implementation(project(":bc:cart"))
    implementation(project(":bc:product"))
    implementation(project(":bc:wishlist"))

    implementation(project(":bc:wallet"))
    implementation(project(":bc:order"))
    implementation(project(":bc:payment"))

    implementation(project(":support:common"))
    implementation(project(":support:logging"))
    implementation(project(":support:security"))
    implementation(libs.spring.boot.starter.security)
    implementation(libs.spring.boot.starter.oauth2.resource.server)
    implementation(project(":support:web"))
    implementation(project(":support:jpa"))
    implementation(libs.dotenv)
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.restclient)
    implementation(libs.spring.boot.jackson2)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.spring.boot.starter.flyway)
    implementation(libs.spring.retry)
    implementation("org.springframework.boot:spring-boot-starter-aspectj")
    implementation(libs.awssdk.s3)
    implementation(libs.spring.boot.starter.batch.jdbc)
    implementation(libs.spring.modulith.kafka)
    implementation(libs.spring.modulith.jpa)
    implementation(libs.spring.modulith.runtime)
    implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch")

    runtimeOnly(libs.h2)
    runtimeOnly(libs.spring.boot.h2console)
    runtimeOnly(libs.postgresql)
    runtimeOnly(libs.flyway.postgresql)
    runtimeOnly(libs.micrometer.prometheus)
    implementation(libs.hibernate.micrometer)
    implementation(libs.java.jwt)
    implementation(libs.micrometer.core)
    implementation(libs.spring.boot.starter.data.redis)
    implementation(libs.spring.boot.starter.oauth2.client)

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    testImplementation(libs.spring.boot.starter.test)
    testImplementation(libs.rest.assured)
    testImplementation("org.springframework.kafka:spring-kafka-test")
    testImplementation("org.springframework.batch:spring-batch-test")
    testImplementation("org.awaitility:awaitility")
    testImplementation(libs.spring.modulith.test)
    testImplementation(libs.spring.modulith.docs)
    testImplementation(libs.archunit)
    testImplementation(libs.spring.boot.starter.webmvc.test)
    testImplementation(libs.spring.security.test)
    testImplementation(libs.testcontainers.junit)
    testImplementation(libs.testcontainers.redis)
    testImplementation(testFixtures(project(":support:common")))
}
