create table friendships (
    accepted_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    receiver_id bigint not null,
    requester_id bigint not null,
    updated_at timestamp(6) not null,
    status varchar(20) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);
