create table settlement_items (
    expected_date date,
    paid_amount numeric(38,2),
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    retry_count integer not null,
    settlement_amount numeric(38,2),
    cancelled_at timestamp(6),
    confirmed_at timestamp(6) not null,
    created_at timestamp(6),
    history_id bigint,
    id bigint generated by default as identity,
    order_id bigint not null,
    order_item_id bigint not null,
    origin_id bigint,
    seller_id bigint not null,
    settled_at timestamp(6),
    target_id bigint not null,
    target_type varchar(50) not null,
    payment_id bigint not null,
    updated_at timestamp(6),
    status varchar(255),
    type varchar(255) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id),
    constraint uk_order_item_id_type unique (order_item_id, type),
    constraint uk_order_id_order_item_id_type unique (order_id, order_item_id, type)
);

create table settlement_queues (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    settlement_item_id bigint not null,
    updated_at timestamp(6),
    status varchar(255) not null,
    primary key (id),
    unique (settlement_item_id),
    constraint fk_settlement_queue_item foreign key (settlement_item_id) references settlement_items
);

create table settlement_histories (
    item_count integer not null,
    pg_fee numeric(38,2),
    platform_fee numeric(38,2),
    sales_amount numeric(38,2),
    settlement_amount numeric(38,2),
    settlement_date date not null,
    id bigint generated by default as identity,
    reference_history_id bigint,
    seller_id bigint not null,
    settled_at timestamp(6),
    status varchar(255),
    primary key (id),
    unique (seller_id, settlement_date)
);

create index idx_settlement_status_created_retry on settlement_items (status, created_at, retry_count);
create index idx_settlement_order_id on settlement_items (order_id);
create index idx_settlement_item_payment_id on settlement_items(payment_id);
create index idx_settlement_item_order_item_id on settlement_items(order_item_id);
create index idx_settlement_item_seller_id on settlement_items(seller_id);
create index idx_settlement_item_history_id on settlement_items(history_id);
