spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN_PROD}/
          jwk-set-uri: https://${AUTH0_DOMAIN_PROD}/.well-known/jwks.json
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID_PROD}
            client-secret: ${AUTH0_CLIENT_SECRET_PROD}
            scope:
              - openid
              - profile
              - email
              - offline_access
        provider:
          auth0:
            issuer-uri: https://${AUTH0_DOMAIN_PROD}/

auth0:
  audience: ${AUTH0_AUDIENCE_PROD}
  domain: ${AUTH0_DOMAIN_PROD}

logging:
  level:
    org.springframework.security: INFO