apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 99
        runAsGroup: 99
      containers:
        - name: redpanda-console
          image: redpandadata/console:v3.5.1
          ports:
            - containerPort: 8180
          env:
            - name: SERVER_LISTENPORT
              value: "8180"
            - name: KAFKA_BROKERS
              value: "redpanda:9092"
            - name: REDPANDA_ADMINAPI_URLS
              value: "http://redpanda:9644"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "300Mi"
          readinessProbe:
            httpGet:
              path: /admin/health
              port: 8180
            initialDelaySeconds: 5
            periodSeconds: 10
