apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v25.1.1
          command:
            - rpk
            - redpanda
            - start
            - --mode
            - dev-container
            - --smp
            - "1"
            - --memory
            - 512M
            - --advertise-kafka-addr
            - redpanda:9092
          ports:
            - name: kafka
              containerPort: 9092
            - name: admin
              containerPort: 9644
            - name: pandaproxy
              containerPort: 8082
          resources:
            requests:
              memory: "384Mi"
              cpu: "200m"
            limits:
              memory: "640Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 10
            periodSeconds: 30
