create table carts (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint unique,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table cart_items (
    amount numeric(38,2),
    cart_id bigint,
    id bigint generated by default as identity,
    target_id bigint,
    target_type varchar(255),
    wishlist_item_status varchar(255),
    primary key (id),
    constraint fk_cart_item_cart foreign key (cart_id) references carts
);
