apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: giftify

resources:
  - namespace.yaml
  # Backend
  - apps/backend/deployment.yaml
  - apps/backend/service.yaml
  # PostgreSQL
  - apps/postgres/statefulset.yaml
  - apps/postgres/service.yaml
  # Redis
  - apps/redis/deployment.yaml
  - apps/redis/service.yaml
  # Prometheus
  - apps/prometheus/configmap.yaml
  - apps/prometheus/deployment.yaml
  - apps/prometheus/service.yaml
  # Grafana
  - apps/grafana/configmap.yaml
  - apps/grafana/deployment.yaml
  - apps/grafana/service.yaml
  # Red-panda
  - apps/redpanda/deployment.yaml
  - apps/redpanda/service.yaml
  - apps/redpanda/console-deployment.yaml
  - apps/redpanda/console-service.yaml
  # k6
  - apps/k6/configmap.yaml
  # Traefik
  - traefik/middleware/rate-limit.yaml
  - traefik/ingress-routes/api.yaml
  - traefik/ingress-routes/monitoring.yaml
  # Cloudflare
  - cloudflare/tunnel-deployment.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - apps/grafana/dashboards/spring-boot-19004.json
      - apps/grafana/dashboards/token-blacklist-security.json
    options:
      disableNameSuffixHash: true
