apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: giftify

resources:
  - namespace.yaml
  # API Server
  - apps/api-server/configmap.yaml
  - apps/api-server/deployment.yaml
  - apps/api-server/service.yaml
  - apps/api-server/hpa.yaml
  - apps/api-server/ingress.yaml
  # PostgreSQL
  - apps/postgres/statefulset.yaml
  - apps/postgres/service.yaml
  # Redis
  - apps/redis/deployment.yaml
  - apps/redis/service.yaml
  # Prometheus
  - apps/prometheus/configmap.yaml
  - apps/prometheus/deployment.yaml
  - apps/prometheus/service.yaml
  - apps/prometheus/ingress.yaml
  # Grafana
  - apps/grafana/configmap.yaml
  - apps/grafana/deployment.yaml
  - apps/grafana/service.yaml
  - apps/grafana/ingress.yaml
  # Red-panda
  - apps/redpanda/deployment.yaml
  - apps/redpanda/service.yaml
  - apps/redpanda/console-deployment.yaml
  - apps/redpanda/console-service.yaml
  - apps/redpanda/ingress.yaml
  # Elasticsearch
  - apps/elasticsearch/statefulset.yaml
  - apps/elasticsearch/service.yaml
  - apps/elasticsearch/ingress.yaml
  # Traefik
  - traefik/middleware/rate-limit.yaml
  - traefik/middleware/forwarded-proto.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - apps/grafana/dashboards/spring-boot-19004.json
      - apps/grafana/dashboards/token-blacklist-security.json
    options:
      disableNameSuffixHash: true
