create table wallets (
    balance numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null unique,
    updated_at timestamp(6) not null,
    version bigint,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table wallet_histories (
    amount numeric(38,2) not null,
    balance_after numeric(38,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    wallet_id bigint not null,
    created_by varchar(255),
    reference_id varchar(255) not null,
    reference_type varchar(255) not null,
    transaction_type varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create index idx_wallet_history_ref on wallet_histories(reference_id, reference_type);
